Fixed editor freezing when providing non-integer colspan or rowspan attributes values
ckeditor/ckeditor5 pull request #10143
Opened 2021-07-13 12:54 UTC by dawidurbanski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix: Fixed editor freezing when providing non-integer colspan or rowspan attributes values. Closes #10042.

---

### Additional information

Can be tested by running `yarn manual --files=table` and checking `tickets/10042.html` test case.

2021-07-13 13:18 UTC, dawidurbanski commented
@niegowski I could also try to remove `( type === 'colspan' && span <= 0 ) || ( type === 'rowspan' && span < 0 )` check and leave it to HTML parser.

2021-07-14 09:17 UTC, niegowski requested changes

2021-07-14 09:17 UTC, niegowski commented on packages/ckeditor5-table/src/tableediting.js
> +		const upcastCellSpan = type => {
This should be extracted to a local function in this module.

2021-07-14 09:17 UTC, niegowski commented on packages/ckeditor5-table/src/tableediting.js
> +				if ( Number.isNaN( span ) || ( type === 'colspan' && span <= 0 ) || ( type === 'rowspan' && span < 0 ) ) {
```suggestion
				if ( Number.isNaN( span ) || span <= 0 ) {
```

2021-07-14 09:17 UTC, niegowski commented on packages/ckeditor5-table/src/tableediting.js
> +					return 1;
```suggestion
					return null;
```

2021-07-14 09:17 UTC, niegowski commented on packages/ckeditor5-table/src/tableediting.js
> +		);
```suggestion
		conversion.for( 'upcast' ).attributeToAttribute( { 
			model: { key: 'colspan', value: upcastCellSpan( 'colspan' ) }, 
			view: 'colspan' 
		} );
```

2021-07-21 08:29 UTC, niegowski commented on packages/ckeditor5-table/src/tableediting.js
> +// Returns fixed colspan and rowspan attrbutes values
```suggestion
// Returns fixed colspan and rowspan attrbutes values.
```

2021-07-21 08:32 UTC, merged