Docs: features output guide formatting.
ckeditor/ckeditor5 pull request #10492
Opened 2021-09-08 06:06 UTC by godai78

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs: formatting changes for the features' output listing. Closes #9700.

---

### Additional information

To do:

*   [x] change plugin and feature names to API docs/feature guides links respectively
*    [x]  add `alt` tag sporting the name of feature/plugin for SEO
*    [ ]  add icons (as described in the original issue)
*    [ ]  test

2021-09-09 09:20 UTC, przemyslaw-zan commented
*   Title is `H4` element - please verify that it's correct element to use
*   I've used 📖 instead of `book.svg`, is that ok?

![](https://user-images.githubusercontent.com/69513154/132658871-705b0e99-4a90-4a0e-afea-41df78114134.png)

2021-09-09 09:29 UTC, godai78 commented
The icon looks fine, both b/w are cool. The title does not need to be `Hx`, a bold will do IMHO.

2021-09-09 10:38 UTC, przemyslaw-zan commented
Now with SVG. I've kept H4:

![](https://user-images.githubusercontent.com/69513154/132670963-3eced39f-c346-4176-9170-1abc8b090c60.png)

Bold would look worse IMO:

![](https://user-images.githubusercontent.com/69513154/132671340-3292bb7c-1b57-478b-bcea-b0b117c4384b.png)

2021-09-09 10:51 UTC, godai78 commented
We need to have the icons aligned. I would opt for black-and-white ones instead of these. Also, I believe the `book` icon is unaligned, so we could use this instead:

![](https://user-images.githubusercontent.com/68123541/132673207-16ed2441-cd6c-4d17-acbc-8f53016d0b19.png)

2021-09-09 11:58 UTC, przemyslaw-zan commented
Inserting new `<h4>` element on top of the table breaks the validator, causing it to throw errors:

![](https://user-images.githubusercontent.com/69513154/132681521-2fee0edf-00f2-4d3b-b33f-1fc5e167b539.png)

Validator likely checks for the first and second element to see if it's the correct linkt - the validator will need adjustment.

2021-09-09 12:36 UTC, pomek commented
> Inserting new `<h4>` element on top of the table breaks the validator, causing it to throw errors

Umberto iterates over heading elements when building a Table of Contents. The `[id]` property for heading elements is obligatory.

2021-09-09 12:39 UTC, pomek commented
> Validator likely checks for the first and second element to see if it's the correct link - the validator will need adjustment.

I checked the changes proposed on the branch and I found the following HTML in the built docs:

```html
<a href="#undefined">CKFinder Upload Adapter</a>
```

There are many of them. The validator works as expected, the produced content seems to be invalid.

2021-09-10 05:48 UTC, psmyrek requested changes
It does not look as it has been proposed:

![Output](https://user-images.githubusercontent.com/56868128/132804594-1abbe05b-87a6-4bb7-84c6-e437c16928f2.png)

- icons are not aligned with the link text,
- both links (feature guide and API docs) should be positioned on the bottom of the cell,
- the `alt` attribute for the API link contains HTML element, i.e. `alt="&lt;code&gt;HorizontalLine&lt;/code&gt;"`,
- the table header should have a light gray background.

Also:
- if the package does not have an API docs link, the script creates an empty `<p>`,
- multiple JSDoc comments should reflect the introduced changes (i.e. the docs for `createFeatureLink()` currently informs that if the feature documentation is missing, just the plugin name is returned, but in fact an empty string is returned).

2021-09-10 05:48 UTC, psmyrek commented on docs/assets/img/exportword.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"><path d="M13 0l5 4.5V20H2V0h11zm-1.5 1.5h-8v17h13v-12h-5v-5zM15 15v1H5v-1h10zm0-3v1H5v-1h10zm0-3v1H5V9h10zm-5-3v1H5V6h5zm3-4v3h3.3L13 2z
The name of this file could reflect its content, i.e. that it represents a book icon.

2021-09-10 06:12 UTC, godai78 commented
I'm not really sure about aligning the links to the bottom for some long cells.

2021-09-13 10:12 UTC, przemyslaw-zan commented
Previously, Feature guide and API docs links were, respectively, plugin name, and plugin class name. After current changes, plugin class name (eg. second link on screenshot below) is not shown anywhere. Do we want to show that somewhere?

![](https://user-images.githubusercontent.com/69513154/133066030-c39c4f2a-dadc-4db0-a214-42f2bd1afea8.png)

2021-09-13 10:17 UTC, przemyslaw-zan commented
I believe script changes are complete. Style changes remaining:

*   icons are not aligned with the link text
*   both links (feature guide and API docs) should be positioned on the bottom of the cell
*   the table header should have a light gray background

2021-09-15 12:51 UTC, pomek commented
The current look:

![image](https://user-images.githubusercontent.com/2270764/133436565-45f037ac-6ba9-4cf4-9141-0ab948bef8cf.png)

2021-09-15 13:15 UTC, merged