Created release script that updates all ckeditor5 dependencies to the latest version.
ckeditor/ckeditor5 pull request #11007
Opened 2021-12-14 17:47 UTC by przemyslaw-zan

Internal: Created release script that updates all \`ckeditor5\` dependencies to the latest version. Closes cksource/ckeditor5-internal#1123.

2021-12-16 09:03 UTC, psmyrek requested changes

2021-12-16 09:03 UTC, psmyrek commented on scripts/release/bump-versions.js
> +// This task must be called before: `npm run release:update-package-versions` and npm `run release:publish`.
```suggestion
// This task must be called before: `npm run release:update-package-versions` and `npm run release:publish`.
```

2021-12-16 09:11 UTC, psmyrek approved these changes
LGTM 🎉 

It should be merged after the `ckeditor5-dev-env` is released and contains changes from https://github.com/ckeditor/ckeditor5-dev/pull/737.

2021-12-17 08:33 UTC, psmyrek approved these changes
LGTM 🎉 

Found just minor cosmetic change to consider.

2021-12-18 15:27 UTC, pomek commented on scripts/release/update-package-versions.js
> +// --diff:      Instead of list of files, it displays detailed list of changes from each file. Has no effect without --dry-run.
Please, merge these options. While the `--dry-run` option makes sense and allows testing what the script will do, I don't understand how it should work when executing `npm run release:update-package-versions -- --diff`.

2021-12-21 08:03 UTC, psmyrek requested changes

2021-12-21 08:03 UTC, psmyrek commented on scripts/release/update-package-versions.js
> +const COLLABORATION_FEATURES_PATH = path.resolve( __dirname, '..', '..', 'external', 'collaboration-features' );
Minor idea to consider: paths to `ckeditor5-internal` and `collaboration-features` could be now based on the `CKEDITOR5_PATH` constant, so when the location of this script changes in the future, only one path to the CKEditor 5 will have to be adapted.

2021-12-21 08:18 UTC, przemyslaw-zan commented on packages/ckeditor5-adapter-ckfinder/package.json
> +    "@ckeditor/ckeditor5-dev-utils": "27.1.0",
Oops, pushed the script-generated commit as a mistake. Will revert this in a second. Why did it changed though... I'll need to investigate whether or not this is a bug in my code.

2021-12-21 08:18 UTC, przemyslaw-zan commented on packages/ckeditor5-adapter-ckfinder/package.json
> +    "webpack-cli": "4.9.0"
Same as https://github.com/ckeditor/ckeditor5/pull/11007#discussion_r772917649

2021-12-21 08:21 UTC, przemyslaw-zan commented on scripts/release/update-package-versions.js
> +			{ path: COLLABORATION_FEATURES_PATH + '/release', commit: false }
I can update this. But I've included `directoryPath.split( '\u005C' ).join( '\u002F' )` in the script itself. Should I remove that safety step, and trust that all arguments passed in the future will be Windows-proof?

2021-12-21 14:56 UTC, pomek commented on scripts/release/update-package-versions.js
> +			{ path: COLLABORATION_FEATURES_PATH + '/release', commit: false }
The script should change only the CKEditor 5 project. Other repositories follow their release steps, and we need to update them. But AFAIR, we wanted to touch only the internal repository, though.

2021-12-21 14:58 UTC, przemyslaw-zan commented on scripts/release/update-package-versions.js
> +			{ path: COLLABORATION_FEATURES_PATH + '/release', commit: false }
So... `ckeditor5/packages` and `ckeditor5/release` only?

2021-12-21 16:27 UTC, pomek commented on scripts/release/update-package-versions.js
> +			{ path: COLLABORATION_FEATURES_PATH + '/release', commit: false }
In `ckeditor5` all updates will be handled by existing release scripts. Hence, we should move this script to the internal repository.

2021-12-30 12:59 UTC, psmyrek commented
Closing because of https://github.com/ckeditor/ckeditor5/pull/11007#discussion_r773278443.

2021-12-30 12:59 UTC, closed without merging