Ck/10812 document list editing
ckeditor/ckeditor5 pull request #11010
Opened 2021-12-15 14:35 UTC by niegowski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Feature (list): Introducing the document list feature. Closes #10812.

Other (engine): The `isAllowedInsideAttributeElement` option was removed, from now on `AttrubuteElement`s are allowed to wrap any view element.

Fix (link): The link decorators should be converted on the block images only once (should not wrap block image with an additional link).

Other (engine): The `Schema` is extended by the new generic type: `$container`. Container elements can contain `$block` or `$container` elements. 

Other (engine): The `DowncastHelpers` are passing an additional parameter to the creator functions (the `data` that provides more context to the element creator callback.

Other (engine): The `ConversionApi` provided by the `UpcastDispatcher` is extended with an additional method `keepEmptyElement` that marks an element that was created during splitting some model element that should not get removed on conversion even if it's empty. 

Other (engine): The `Differ` change entries for `insert` and `remove` types are extended with a map of attributes that were set while inserting an element or that were on an element while it got removed.

MINOR BREAKING CHANGE (engine): The `isAllowedInsideAttributeElement` option is removed so `AttributeElement`s can wrap any view element (according to positions). Make sure that you are not wrapping any `ContainerElement` by an accident by not checking the target in the converter. Those would previously get wrapped by an `AttributeElement` that immediately would be removed by the `ContainerElement` within it so there would not be any visual effect.

---

### Additional information

2021-12-22 12:49 UTC, oleq requested changes
1. Let's merge it to a new feature branch instead of master.
2. Because the indent command branch contains improvements and refactoring of some fragments of code mentioned in this review, let's apply changes there and avoid doing the same thing twice.

2021-12-22 12:49 UTC, oleq commented on packages/ckeditor5-list/src/documentlist/converters.js
> +		}
Let's make a named helper out of it.

2021-12-22 12:49 UTC, oleq commented on packages/ckeditor5-list/src/documentlist/converters.js
> +		}
Do we need to create all these helpers every time `change:data` kicks in? I'd extract them somewhere else.

2021-12-28 10:01 UTC, Reinmar commented on packages/ckeditor5-html-support/tests/htmlcomment-integration.js
> +					'<img src="/assets/sample.png" alt="Example image">' +
This test didn't work on the feature branch, but we didn't notice  this so far. So, it's unrelated to this PR.

2021-12-28 10:05 UTC, Reinmar commented on packages/ckeditor5-link/src/linkediting.js
> +					if ( !schema.isInline( item ) ) {
```suggestion
					// Manual decorators for block links are handled e.g. in LinkImageEditing.
					if ( !schema.isInline( item ) ) {
```

2021-12-28 10:11 UTC, Reinmar commented on packages/ckeditor5-link/src/utils/automaticdecorators.js
> +				if ( !( data.item.is( 'selection' ) || conversionApi.schema.isInline( data.item ) ) ) {
```suggestion
				// Automatic decorators for block links are handled e.g. in LinkImageEditing.
				if ( !( data.item.is( 'selection' ) || conversionApi.schema.isInline( data.item ) ) ) {
```

2022-02-24 15:01 UTC, CatStrategist commented
@ckeditor/qa-team 

First milestone for Document Lists is ready for tests. You can access it on `ck/10812-document-list-editing` branch in list's package manual test `document-list`.

Ready and most important things to test are:
- Creating bulleted/numbered lists
- Multi-block list items
- Mixing bulleted/numbered lists
- Handling enter key and creating new list items
- Handling delete/backspace
- Indenting/Outdenting list items through UI Button and Tab/Shift+Tab keys
- List navigation
- Order of commands' execution. E.g. table as a list item and selection is inside table's cell - table tab handler should react to keystroke. (Whatever is closest to selection).
- Setting/getting document lists through setData/getData
- Verify correct behaviour when working with multiple lists, e.g. merge two lists
- Inserting and behaviour of widgets as a list item. Currently you can't insert widgets directly as a list item, it's a known bug. To make widget a list item you must first create it out of a list and then make it a list with bulleted/numbered list button.
- Verify if old lists aren't broken
- Test nesting lists in a block quote/tabels 
- Test nesting block quote/tabels in a list

Except for finding bugs we would welcome feedback on UX. Please share any ideas you might have about improving behaviour of a document lists as well as anything that bothered you or seems off. :)

If you have any questions please let me know!

2022-02-25 09:57 UTC, CatStrategist commented
@Mgsy Please link all related bugs in this pull request.

2022-02-25 11:59 UTC, Mgsy commented
## Plugins conflict

It's impossible to use `DocumentList` feature along with `TodoList` and `ListProperties` plugins, as these require `ListEditing` resulting in conflict between `DocumentListEditing`.

2022-02-28 09:12 UTC, FilipTokarski commented
Cannot remove a widget which is a list item - https://github.com/ckeditor/ckeditor5/issues/11346

2022-02-28 09:23 UTC, FilipTokarski commented
List items are not removed correctly with backspace - https://github.com/ckeditor/ckeditor5/issues/11347

2022-02-28 09:50 UTC, FilipTokarski commented
Error when removing formatting on text - https://github.com/ckeditor/ckeditor5/issues/11348

2022-02-28 10:09 UTC, FilipTokarski commented
Error after getting data with html comment in list item - https://github.com/ckeditor/ckeditor5/issues/11350

2022-02-28 10:10 UTC, LukaszGudel commented
Image is inserted incorrectly with drag&drop into paragraph in list - https://github.com/ckeditor/ckeditor5/issues/11351

2022-02-28 10:21 UTC, LukaszGudel commented
Removing widget breaks the document list - https://github.com/ckeditor/ckeditor5/issues/11352

2022-02-28 10:41 UTC, FilipTokarski commented
Cannot insert text before or after a widget inside a list item - https://github.com/ckeditor/ckeditor5/issues/11353

2022-02-28 10:56 UTC, LukaszGudel commented
Error after getting data with code block in list - https://github.com/ckeditor/ckeditor5/issues/11354

2022-02-28 10:57 UTC, FilipTokarski commented
List gets split when widget is pasted/dropped into the list item - https://github.com/ckeditor/ckeditor5/issues/11355

2022-02-28 14:11 UTC, FilipTokarski commented
List items misaligned and covered after aligning table to the left - https://github.com/ckeditor/ckeditor5/issues/11361

2022-03-01 14:47 UTC, LukaszGudel commented
I've created a single ticket for our UX feedback. We will add new comments there - https://github.com/ckeditor/ckeditor5/issues/11371

2022-03-01 15:09 UTC, dufipl commented
Image with captions split list: https://github.com/ckeditor/ckeditor5/issues/11374

2022-03-02 17:15 UTC, dufipl commented
Blockquote does not work with document-list https://github.com/ckeditor/ckeditor5/issues/11383

2022-03-02 17:29 UTC, dufipl commented
Drag and dropping or pasting the table into the table cell with document list inside clears cell content: https://github.com/ckeditor/ckeditor5/issues/11384

2022-03-02 17:52 UTC, dufipl commented
Media embed does not work with document-list: https://github.com/ckeditor/ckeditor5/issues/11386

2022-03-22 15:08 UTC, niegowski commented
Closing this PR as code moved to epic branch #11503

2022-03-22 15:08 UTC, closed without merging