[WIP] Migrate to b͓̲̐͐͐̐̑e̩̼͕͈̗ͥ̄̑f̲̮̠ͯor̗̲͕̝ͨ̑̆̉͆e̬̜inp̖̗̦͆ͤu̗̞̬̺̮t͎
ckeditor/ckeditor5 pull request #11456
Opened 2022-03-11 14:50 UTC by oleq

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

WIP

2022-03-17 13:34 UTC, dufipl commented
@oleq,
`shift` + `enter` doesn't work correctly on Safari. It behaves just like pressed only `enter`. 
On Firefox and Chrome, it works fine.
It is a regression, on master it behaves correctly.

2022-03-18 08:18 UTC, Mgsy commented
I love that finally CMD + backspace works :tada:. However, I've found one issue related to this feature.

### Firefox

1.  Put the caret at the end of a single-line paragraph.
2.  Press CMD + backspace.
3.  Repeat step 2.

The editor crashes.

```
Uncaught TypeError: selection.getFirstRange() is null
    execute deletecommand.js:121
    _runPendingChanges model.js:848
    enqueueChange model.js:253
    execute deletecommand.js:77
    decorate observablemixin.js:258
    fire emittermixin.js:199
    methodName observablemixin.js:262
    execute commandcollection.js:69
    execute editor.js:295
    init delete.js:72
    fire emittermixin.js:199
    fireListenerFor bubblingemittermixin.js:162
    fire bubblingemittermixin.js:92
    DeleteObserver deleteobserver.js:182
    fire emittermixin.js:199
    fireListenerFor bubblingemittermixin.js:162
    fire bubblingemittermixin.js:92
    fire domeventobserver.js:96
    onDomEvent inputobserver.js:58
    observe domeventobserver.js:79
    fire emittermixin.js:199
    domListener emittermixin.js:293
    attach emittermixin.js:219
    _addEventListener emittermixin.js:264
    addEventListener emittermixin.js:701
    listenTo emittermixin.js:117
    listenTo emittermixin.js:68
    listenTo emittermixin.js:65
    observe domeventobserver.js:77
    observe domeventobserver.js:76
    attachDomRoot view.js:287
    init classiceditorui.js:104
    create classiceditor.js:205
```

Works fine in Chrome/Safari.

2022-03-18 12:15 UTC, dufipl commented
I've found an issue with Safari on iPad and it is a regression:
On iPad there are undo/redo buttons at the keyboard:
![IMG_071859E45D09-1](https://user-images.githubusercontent.com/32898551/159001155-c5594ddc-c3c5-4355-9dd7-1de15a3a4f47.jpeg)
On `master` they are not working when e.g. new line is added, but they are working when text is added.
On `ck/epic/11438-migrate-to-beforeinput` those buttons are not working anymore, even when text is being written.

2022-03-18 14:34 UTC, FilipTokarski commented
### Android Gboard

1. Place caret at the end of a heading
2. Type

```js
Uncaught CKEditorError: model-nodelist-offset-out-of-bounds {"offset":19,"nodeList":[{"data":"Lists in the table"}]}
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-nodelist-offset-out-of-bounds
    at NodeList.offsetToIndex (nodelist.js:161:1)
    at Element.offsetToIndex (element.js:186:1)
    at getTextNodeAtPosition (position.js:1100:1)
    at Position.get textNode [as textNode] (position.js:218:1)
    at validateTextNodePosition (document.js:482:1)
    at Document._validateSelectionRange (document.js:391:1)
    at LiveSelection.<anonymous> (documentselection.js:666:1)
    at LiveSelection.fire (emittermixin.js:199:1)
    at LiveSelection._setRanges (selection.js:471:1)
    at LiveSelection.setTo (selection.js:370:1)
```


https://user-images.githubusercontent.com/34380544/159022138-c3a4c7fc-c98f-4fb6-8836-5fce43260212.mp4

2022-03-18 14:57 UTC, FilipTokarski commented
### Android Swift keyboard

1. Select whole world
2. Change it to the one suggested by keyboard spellchecker

```js
Uncaught CKEditorError: insert-operation-position-invalid
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-insert-operation-position-invalid
    at InsertOperation._validate (insertoperation.js:117:1)
    at Model.on.priority (model.js:91:1)
    at Model.fire (emittermixin.js:199:1)
    at Model.<computed> [as applyOperation] (observablemixin.js:262:1)
    at Writer.insert (writer.js:219:1)
    at Insertion._insertPartialFragment (insertcontent.js:373:1)
    at Insertion.handleNodes (insertcontent.js:226:1)
    at insertcontent.js:76:1
    at Model.change (model.js:187:1)
    at insertContent (insertcontent.js:51:1)

Uncaught CKEditorError: model-nodelist-offset-out-of-bounds {"offset":11,"nodeList":[{"data":"Hello "}]}
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-nodelist-offset-out-of-bounds
    at NodeList.offsetToIndex (nodelist.js:161:1)
    at Element.offsetToIndex (element.js:186:1)
    at getTextNodeAtPosition (position.js:1100:1)
    at Position.get textNode [as textNode] (position.js:218:1)
    at validateTextNodePosition (document.js:482:1)
    at Document._validateSelectionRange (document.js:391:1)
    at LiveSelection.<anonymous> (documentselection.js:666:1)
    at LiveSelection.fire (emittermixin.js:199:1)
    at LiveSelection._setRanges (selection.js:471:1)
    at LiveSelection.setTo (selection.js:370:1)
```


https://user-images.githubusercontent.com/34380544/159026666-4b7a9257-489d-48f6-bc01-57296b23fa14.mp4

2022-03-18 15:06 UTC, FilipTokarski commented
### Android GBoard

1. Press `enter` at the end of paragraph and type something

Empty paragraphs are created below, but selection is still in the same place. On `master` it's even more weird - you need to press `enter` twice to create a new paragraph, but then typing works fine.


https://user-images.githubusercontent.com/34380544/159028352-ddf2b68a-5b75-4359-9476-fddc1e39e2c0.mp4

2022-03-21 09:06 UTC, FilipTokarski commented
## CHROME

### Steps

1. Select table cells that contain image (or other widget).
2. Press `backspace` or `delete`.

### Expected
All content from selected cells gets deleted:


https://user-images.githubusercontent.com/34380544/159230988-90e0af7b-5272-4271-b485-9b9bb50ea15f.mp4



### Actual
Nothing happens:


https://user-images.githubusercontent.com/34380544/159231010-42e7fd86-432d-4af3-81a7-d8ca14f03d9b.mp4

2022-03-21 10:53 UTC, dufipl commented
The above ⬆️ issue reproduces also on Safari (on Firefox it works as expected).

2022-05-12 21:03 UTC, Reinmar commented
FYI: the latest work is in branch `ck/11438-beforeinput-ime-research-vol1.1`.

Shouldn't this PR be closed?

2022-05-13 11:17 UTC, niegowski commented
> Shouldn't this PR be closed?

No. This is a feature branch and those IME research branches are based on this feature branch.

2022-10-13 10:34 UTC, arkflpc requested changes

2022-10-13 10:34 UTC, arkflpc commented on packages/ckeditor5-engine/src/view/datatransfer.ts
> +	public readonly files: File[];
```suggestion
	public readonly files: Array<File>;
```

2022-10-13 10:34 UTC, arkflpc commented on packages/ckeditor5-engine/src/view/view.ts
> +		this.addObserver( InputObserver );
Twice?

2022-10-13 10:34 UTC, arkflpc commented on packages/ckeditor5-engine/tests/view/view/view.js
> +		expect( view.getObserver( InputObserver ) ).to.be.instanceof( InputObserver );
Twice?

2022-10-13 10:34 UTC, arkflpc commented on packages/ckeditor5-typing/tests/manual/beforeinput.md
> +* [Typing events - scenario](https://www.notion.so/Typing-events-scenarios-8d750fcdc8984e4fa5126e78b98e4047)
Does it make sense to put in the public repo links to private Notion?

2022-10-13 10:36 UTC, arkflpc approved these changes

2022-10-13 11:59 UTC, merged

2022-11-02 11:41 UTC, niegowski commented
> MINOR BREAKING CHANGE: The `input` command is now deprecated, you should use `insertText` command instead.

To give some more background. This PR is changing the input flow, so the editor is now using the `beforeInput` events instead of DOM mutation-based input. The previous command (`input`) is still available as an alias and the same options should be accepted by both commands.