Keyboard support for special characters dropdown grid
ckeditor/ckeditor5 pull request #12257
Opened 2022-08-10 16:06 UTC by mmotyczynska

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Type: Message. Closes #9037.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2022-08-15 16:28 UTC, mmotyczynska commented
After setting the row to always contain 10 items (CSS: `grid-template-columns: repeat(10, 1fr)`) I also changed `overflow-x` to `auto` because in small screens (e.g. mobile) the items of the grid at the end of the row were not visible.

2022-08-16 16:30 UTC, mmotyczynska commented
There is still one issue to be fixed: updating info section when navigating with keyboard.

For now, the info section is updated on mouseover. We should also update it when navigating with arrow keys. So there are two cases to be discussed (the 1st one depends on the 2nd):

1. If on `mouseover` the info section is being changed, what should happen on `mouseout`? Should we update the info section based on the currently focused tile (for now focus is changed only when navigating with keyboard)?
2. Should the `mouseover` also `focus` the tile? If so, then we wouldn't have to think about 1. because the mouse would take over the current selection.

2022-08-17 18:22 UTC, mmotyczynska commented
> setting the row to always contain 10 items (CSS: `grid-template-columns: repeat(10, 1fr)`)

This also causes the special characters grid to be not fully visible in some mobile devices. So for smaller screens I changed the number of items from 10 to 7 in a single row which solves the issue for the 2 android devices a tested. Changing the number to be less than 7 is still possible but would require more adjustments in CSS. This is because at some point the header section does not have enough space for the title and category dropdown.

![](https://user-images.githubusercontent.com/95343030/185212872-cf3c27a4-04e3-4336-9a77-7bae0e11db8b.png)

Unfortunately navigation with keyboard is not dynamic, i.e. it does not check the number of items in a row in runtime but always operates on the hardcoded value for the given feature (for special characters this is equal 10). As a result, on smaller devices when the number of items will be other than 10 (7 in our case), the navigation with arrow up/down will be broken. However it is rather not a common case to use keyboard with small screens so we can improve this in the future.

2022-08-22 09:12 UTC, oleq commented on packages/ckeditor5-special-characters/tests/ui/charactergridview.js
> +	describe( 'FocusTracker', () => {
Let's move it to `render()` section where it happens in the code.

2022-08-22 09:14 UTC, oleq requested changes
The feature looks OK. There are some tests missing, though and some docs too. 

BTW, I added the support for responsive grids in the keyboard navigation helper because it turned out very easy and works fine with the special chars grid.

2022-08-23 13:47 UTC, merged