Docs: the undo/redo guide.
ckeditor/ckeditor5 pull request #12358
Opened 2022-08-29 11:38 UTC by godai78

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs: add the undo/redo guide. Closes #12301

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2022-08-30 07:40 UTC, Reinmar commented
![](https://user-images.githubusercontent.com/156149/187378563-45de547e-894c-443c-9a3f-fadebd4f6fde.png)

When documenting plugins make it clear that these are plugins. In the current proposal `UndoEditing` is described to be a class and `Undo` as a feature. `UndoUI` actually lacks any word :D

2022-08-30 07:41 UTC, Reinmar commented
I left some inspiration in #12301.

2022-08-31 12:03 UTC, apadol-cksource requested changes

2022-08-31 12:07 UTC, godai78 commented on packages/ckeditor5-undo/docs/features/undo-redo.md
> +# Undo/Redo support
Addressed in the commit.

2022-08-31 12:07 UTC, apadol-cksource approved these changes

2022-08-31 12:07 UTC, godai78 commented on packages/ckeditor5-undo/docs/features/undo-redo.md
> +The undo features lets the user withdraw recent changes done to the editor content, as well as bring them back again. All operations are remembered and organized info batches, that can later be easil
Addressed in the commit.

2022-08-31 13:12 UTC, merged