Fix (link): Don't undo autolinking when any other change has been made.
ckeditor/ckeditor5 pull request #12460
Opened 2022-09-13 07:39 UTC by kbinieda

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (link): Don't undo autolinking when any other change has been made. Closes #11040.

2022-09-13 11:57 UTC, scofalik commented
As far as I can see, the fix here is to prevent additional auto-linking of already linked text. AFAICS, This can happen in two scenarios:

* when you move selection before the link and type space again,
* when you start removing text, e.g. `http://foo.pl abc[]` -> `http://foo.pl []`.

I am quite sure that we don't want to double auto-link in such cases :).

However, I have two thoughts regarding this.

One, I wonder if `TextWatcher` should fire an event on text deletion. IDK if there are cases where this could be useful/used. In general, if you are deleting stuff, you must have added it earlier, which means that the `TextWatcher` already had a chance to act. Unless you pasted some text (e.g. you pasted `lorem http://foo.pl ipsum`). But in this case, AFAIK, we don't want `TextWatcher` to autolink after removing `ipsum` right? So, maybe we should also change how `TextWatcher` works? Nevertheless, the proposed if will help in the first case (moving selection before the link and typing space again).

Second, I think that I'd add one more unit test. Proposed unit test is fine, as it targets exactly the scenario described in the ticket. However, I'd add one more unit test, that would make sure that we don't autolink already linked text (you can use the scenario with moving selection and typing space again). This test will target the actual change.

cc @Reinmar (regarding `TextWatcher`).

2022-09-13 11:57 UTC, scofalik requested changes
Please add one more test (as described in my previous comment).

2022-09-14 13:12 UTC, kbinieda commented
Aside from adding additional test, I've broke down _applyAutoLink function so that the moment of applying linkHref can be easily tested.

2022-09-14 14:01 UTC, scofalik requested changes
Small fixes required.

2022-09-14 14:01 UTC, scofalik commented on packages/ckeditor5-link/tests/autolink.js
> +		it( 'should not undo auto-linking by pressing backspace after any other change has been made', () => {
Could you add a link to the issue in the comment above this line? This test will seem very weird to someone looking at it in a year :).

2022-09-14 14:37 UTC, kbinieda commented on packages/ckeditor5-link/tests/autolink.js
> +		it( 'does not autolink if link is already created', () => {
That's a good point. The "different text" approach gives us different result which we can then easily compare, I haven't thought of that. On the other hand If we want to check if same text/link hasn't been applied twice I would go for a method spy as it is more readable than operations counting.

2022-09-15 09:19 UTC, Reinmar commented
> One, I wonder if `TextWatcher` should fire an event on text deletion. IDK if there are cases where this could be useful/is already used. In general, if you are deleting stuff, you must have added it earlier, which means that the `TextWatcher` already had a chance to act. Unless you pasted some text (e.g. you pasted `lorem http://foo.pl ipsum`). But in this case, AFAIK, we don't want `TextWatcher` to autolink after removing `ipsum` right? So, maybe we should also change how `TextWatcher` works?

TextWatcher is also used by mentions. I tested quickly how mentions work e.g. in Slack and when you start with this:

```
Hello, @reinmarX[]
```

And press delete, the mention panel will be triggered once "X" is removed.

Our current implementation, from what I quickly tested, works the same way as Slack's. So I consider this correct.

However, there's a chance that TextWatcher should indeed be improved. For instance, if you a content like this in GH Writer:

```
Text[]
#123
#234
Text
```

And start to navigate through this content with the up/down arrows, you'll be constantly triggering mentions, blocking the navigation. GH's native editor does not have this shortcoming. But... Slack's has if you have content with unfinished mentions:

```
Hello, @re[]
Hello, @re
```

Long story short, I'd be really cautious when changing something, but there's a chance that we should.

There's also a chance that autolink should work differently than mentions.

2022-09-15 09:20 UTC, Reinmar commented on packages/ckeditor5-link/src/autolink.js
> +	 * Enqueue autolink changes in model.
```suggestion
	 * Enqueue autolink changes in the model.
```

2022-09-15 09:54 UTC, scofalik commented
I forgot that `TextWatcher` has uses outside of autoformatting text.

> There's also a chance that autolink should work differently than mentions.

Yes. But having mentions in mind, it seems that it is better to add modifications in auto-formatting features (autoformat, autolink, etc.) if needed. We could also manage this behavior through an option parameter when creating `TextWatcher` instance (to what it should react: typing, deleting, selection change).

But this is outside of the scope of this PR. I will create a new issue for this discussion.

2022-09-15 11:48 UTC, merged