Docs: Added meaningful comments to ellipses in installing plugins guide.
ckeditor/ckeditor5 pull request #13073
Opened 2022-12-15 07:51 UTC by ldrobnik

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs: Added meaningful comments to ellipses in installing plugins guide. Closes [#13039](https://github.com/ckeditor/ckeditor5/issues/13039).

---

### Additional information

Added explanatory comments to ellipses in a code snippet in the installing plugins guide.

2022-12-15 13:56 UTC, dufipl requested changes
I've prepared inline suggestions that, if you agree, you may commit directly from the GitHub. They are based on the fact, that this particular example of code is just used to explain something and is based on the existing code of `ckeditor5-build-classic` (https://github.com/ckeditor/ckeditor5-build-classic/blob/stable/src/ckeditor.js) so the user is not expected to copy it or change anything within. Consequently, we should just describe what is in these places of files where ellipses were used (as they were used in order to shorten the code example).

2022-12-15 13:56 UTC, dufipl commented on docs/installation/getting-started/installing-plugins.md
> +	// Here you should add all the other plugins you want to include in the build.
Same as above ☝️, the user is rather not expected to modify something here in this guide, so we inform him what would be here in the full version of the file using almost the same words as in the original source: https://github.com/ckeditor/ckeditor5-build-classic/blob/0501682eced14cb7d362d8f21228be852cd90a92/src/ckeditor.js#L35

2022-12-15 13:56 UTC, dufipl commented on docs/installation/getting-started/installing-plugins.md
> +			// Add the remaining toolbar items here.
```suggestion
			// Remaining toolbar items.
```

2022-12-15 13:56 UTC, dufipl commented on docs/installation/getting-started/installing-plugins.md
> +			// Add the remaining toolbar items here.
As above comments ☝️

2022-12-15 13:56 UTC, dufipl commented on docs/installation/getting-started/installing-plugins.md
> +	// Specify additional configuration here.
```suggestion
	// Rest of classic editor configuration. 
```

2022-12-15 13:56 UTC, dufipl commented on docs/installation/getting-started/installing-plugins.md
> +	// Specify additional configuration here.
As above comments ☝️

2022-12-16 07:06 UTC, ldrobnik commented on docs/installation/getting-started/installing-plugins.md
> +// Add the remaining imports here.
Much better. Thanks for this. I was wondering what style I should choose.

2022-12-16 07:07 UTC, ldrobnik commented on docs/installation/getting-started/installing-plugins.md
> +	// Here you should add all the other plugins you want to include in the build.
Your suggestion makes much more sense. Many thanks!

2022-12-16 07:08 UTC, ldrobnik commented on docs/installation/getting-started/installing-plugins.md
> +			// Add the remaining toolbar items here.
Thank you!

2022-12-16 07:08 UTC, ldrobnik commented on docs/installation/getting-started/installing-plugins.md
> +	// Specify additional configuration here.
Many thanks!

2022-12-16 08:53 UTC, dufipl approved these changes
LGTM 🎉

2022-12-16 08:54 UTC, dufipl requested changes
Unfortunately, now I see that PR is set to be merged to 'master', whereas it should be merged to 'stable'. We should close it and create another one.

2022-12-16 08:56 UTC, ldrobnik commented
Oh no, my bad. Sorry! I'll create a new one.

2022-12-16 08:56 UTC, dufipl commented
Closing as the wrong branch is set to be merged into. @ldrobnik please create a new one in order to merge from your branch to the `stable` and add me to the final review :)

2022-12-16 08:56 UTC, closed without merging