Docs: Move content from advanced to getting started.
ckeditor/ckeditor5 pull request #13170
Opened 2022-12-29 08:20 UTC by gorzelinski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs: Move content from advanced to getting started.
Closes https://github.com/cksource/ckeditor5-internal/issues/2373

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-01-03 22:37 UTC, apadol-cksource approved these changes
The change looks more than good to me. The outcome is exactly as expected. We could potentially change the order of the articles in TOC as I have a feeling that getting and setting data is used more often than listening to changes in the editor but we can easily change it later. Let's double check it with extra set of eyes as there is plenty of changes in many places. Maybe somebody from QA?

2023-01-05 16:44 UTC, dufipl requested changes
Suddenly, demos are not working here: http://127.0.0.1:8080/ckeditor5/35.4.0/installation/getting-started/getting-and-setting-data.html#demo 
## Expected:
<img width="895" alt="image" src="https://user-images.githubusercontent.com/32898551/210832759-a0634eca-6076-40a8-a73e-42d4a373874e.png">
## Actual:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/32898551/210832849-82cbdb78-8623-460d-a58c-0a9b36c0b712.png">

Similar for: 
http://127.0.0.1:8080/ckeditor5/35.4.0/installation/getting-started/getting-and-setting-data.html#demo-2

## Additional info
Errors are present in the console:
```
Uncaught ReferenceError: ClassicEditor is not defined
    at eval (autosave.js:18:1)
    at ./node_modules/umberto/source/ckeditor5/35.4.0/_snippets/installation/getting-and-setting-data/autosave.js (snippet.js:23:1)
    at __webpack_require__ (snippet.js:57:41)
    at snippet.js:97:37
    at snippet.js:99:12
manualsave.js:19 Uncaught ReferenceError: ClassicEditor is not defined
    at eval (manualsave.js:19:1)
    at ./node_modules/umberto/source/ckeditor5/35.4.0/_snippets/installation/getting-and-setting-data/manualsave.js (snippet.js:23:1)
    at __webpack_require__ (snippet.js:57:41)
    at snippet.js:97:37
    at snippet.js:99:12
```

2023-01-09 14:08 UTC, dufipl commented on docs/installation/getting-started/getting-and-setting-data.md
> +# Getting and setting data
Build import was missing here. It should look like that:
```suggestion
{@snippet installation/getting-and-setting-data/build-autosave-source}

# Getting and setting data
```

2023-01-10 12:58 UTC, dufipl commented on docs/installation/getting-started/getting-and-setting-data.md
> +# Getting and setting data
Fixed in https://github.com/ckeditor/ckeditor5/pull/13170/commits/d015ea071852c953517943f1f1d886baa027296b.

2023-01-10 16:50 UTC, dufipl requested changes

2023-01-10 16:50 UTC, dufipl commented on docs/installation/getting-started/predefined-builds.md
> +	The `build/ckeditor.js` file is generated in the [UMD format](https://github.com/umdjs/umd) so you can also import it into your application if you use CommonJS modules (like in Node.js) or AMD modul
We refer to the Basic API guide that doesn't exist anymore. We should rephrase that.

```suggestion
	The `build/ckeditor.js` file is generated in the [UMD format](https://github.com/umdjs/umd) so you can also import it into your application if you use CommonJS modules (like in Node.js) or AMD modules (like in Require.js). Read more in the {@link installation/getting-started/predefined-builds#umd-support UMD support section guide}.
```

2023-01-10 16:50 UTC, dufipl commented on docs/updating/migration-from-ckeditor-4.md
> +The API for integrating CKEditor with your pages also changed. It is worth checking {@link installation/getting-started/editor-lifecycle Editor Lifecycle} and @link installation/getting-started/save-
This link is wrong.
```suggestion
The API for integrating CKEditor with your pages also changed. It is worth checking {@link installation/getting-started/editor-lifecycle Editor Lifecycle} and @link installation/getting-started/getting-and-setting-data Getting and setting data} for an introduction.
```

2023-01-10 16:50 UTC, dufipl commented on docs/installation/migration-from-ckeditor-4.md
> +The API for integrating CKEditor with your pages also changed. It is worth checking {@link installation/getting-started/editor-lifecycle Editor Lifecycle} and @link installation/getting-started/save-
This link is wrong.
```suggestion
The API for integrating CKEditor with your pages also changed. It is worth checking {@link installation/getting-started/editor-lifecycle Editor Lifecycle} and @link installation/getting-started/getting-and-setting-data Getting and setting data} for an introduction.
```

2023-01-11 08:36 UTC, dufipl commented on docs/updating/migration-from-ckeditor-4.md
> +The API for integrating CKEditor with your pages also changed. It is worth checking {@link installation/getting-started/editor-lifecycle Editor Lifecycle} and @link installation/getting-started/save-
@gorzelinski we still miss this one ☝️

2023-01-11 15:40 UTC, dufipl approved these changes
LGTM 🎉

2023-01-12 12:21 UTC, merged