Rewrite minimap to TypeScript
ckeditor/ckeditor5 pull request #13232
Opened 2023-01-10 09:29 UTC by mremiszewski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Other (minimap): Rewrite ckeditor5-minimap to TypeScript. Closes #13025.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-01-11 14:05 UTC, arkflpc requested changes
Changes in package.json are missing.

2023-01-11 14:05 UTC, arkflpc commented on packages/ckeditor5-minimap/src/minimapview.ts
>  	 * @readonly
```suggestion
	 * Returns the DOM {@link module:utils/dom/rect~Rect} height of the minimap.
```

2023-01-11 14:05 UTC, arkflpc commented on packages/ckeditor5-minimap/src/minimapview.ts
> +	args: [percentage: number];
```suggestion
	args: [ percentage: number ];
```

2023-01-11 14:05 UTC, arkflpc commented on packages/ckeditor5-minimap/src/minimapview.ts
> +	args: [movementY: number];
```suggestion
	args: [ movementY: number ];
```

2023-01-11 14:05 UTC, arkflpc commented on packages/ckeditor5-minimap/src/utils.ts
>   * @protected
```suggestion
 * @internal
```

2023-01-11 14:05 UTC, arkflpc commented on packages/ckeditor5-minimap/src/utils.ts
>   * @protected
```suggestion
 * @internal
```

2023-01-11 14:05 UTC, arkflpc commented on packages/ckeditor5-minimap/src/utils.ts
> +export function getPageStyles(): Array<string | object> {
```suggestion
export function getPageStyles(): Array<string | { href: string }> {
```

2023-01-11 14:05 UTC, arkflpc commented on packages/ckeditor5-minimap/src/utils.ts
>   * @protected
```suggestion
 * @internal
```

The same for functions below.

2023-01-11 14:05 UTC, arkflpc commented on packages/ckeditor5-minimap/src/utils.ts
>   * TODO
Either add comments or remove TODO. IMO, it shouldn't be in API docs.
The same for functions below

2023-01-11 15:41 UTC, arkflpc commented on packages/ckeditor5-minimap/src/minimapiframeview.ts
> +		const iframeDocument = ( this.element as any ).contentWindow.document;
Change `IframeView` to extend `View<HTMLIFrameElement>` instead of `View` and the cast to any won't be needed.

2023-01-12 18:56 UTC, mremiszewski commented
> Changes in package.json are missing.

I think you meant changes in `.gitignore` file. So I fixed it.

2023-01-17 07:17 UTC, arkflpc approved these changes

2023-01-17 07:17 UTC, merged