Rewrite media-embed to typescript.
ckeditor/ckeditor5 pull request #13335
Opened 2023-01-25 14:42 UTC by mremiszewski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Other (media-embed): Rewrite `ckeditor5-media-embed` to Typescript. Closes #13023.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-01-25 15:53 UTC, niegowski requested changes
Also missing changes to `.gitignore` file.

2023-01-25 15:53 UTC, niegowski commented on packages/ckeditor5-media-embed/src/mediaembed.ts
> +import '../theme/mediaembed.css';
CSS should be imported at the end of imports block.

2023-01-25 15:53 UTC, niegowski commented on packages/ckeditor5-media-embed/src/automediaembed.ts
> +	public static get pluginName(): 'AutoMediaEmbed' {
Please augment `PluginsMap`.

2023-01-25 15:53 UTC, niegowski commented on packages/ckeditor5-media-embed/src/mediaembedcommand.ts
> + * Checks if the table is allowed in the parent.
```suggestion
 * Checks if the media embed is allowed in the parent.
```

2023-01-25 15:53 UTC, niegowski commented on packages/ckeditor5-media-embed/src/mediaembedediting.ts
> +import type { UpcastElementEvent } from 'ckeditor5/src/engine';
Please keep imports from `ckeditor5/src/...` next to one another.

2023-01-25 15:53 UTC, niegowski commented on packages/ckeditor5-media-embed/src/mediaembedediting.ts
> +		// eslint-disable-next-line @typescript-eslint/consistent-type-assertions
Why is this needed?

2023-01-25 15:53 UTC, niegowski commented on packages/ckeditor5-media-embed/src/mediaembedediting.ts
> +				};
```suggestion
				};

```

2023-01-25 15:53 UTC, niegowski commented on packages/ckeditor5-media-embed/src/mediaembedtoolbar.ts
> +{
```suggestion
declare module './mediaembed' {
```

2023-01-25 15:53 UTC, niegowski commented on packages/ckeditor5-media-embed/src/mediaembedui.ts
> +			form.urlInputView.bind( 'isEnabled' ).to( command, 'isEnabled' );
I would expect that this code worked previously so please make sure that this change is needed.

2023-01-25 15:53 UTC, niegowski commented on packages/ckeditor5-media-embed/src/mediaregistry.ts
> +	protected _getMedia( url: string ): Media | null {
Is this method used anywhere in overriding class? If not maybe it should be `private`?

2023-01-25 15:53 UTC, niegowski commented on packages/ckeditor5-media-embed/src/mediaregistry.ts
>   * @private
This is not needed. This class is not exported.

2023-01-25 15:53 UTC, niegowski commented on packages/ckeditor5-media-embed/src/mediaregistry.ts
> +	private _previewRenderer?: Function;
Can we provide some more detailed type (not `Function`)?

2023-01-25 15:53 UTC, niegowski commented on packages/ckeditor5-media-embed/src/utils.ts
> +		writer.createSlot( 'children' )
```suggestion
		writer.createSlot()
```

2023-01-25 15:53 UTC, niegowski commented on packages/ckeditor5-media-embed/src/utils.ts
> +};
Missing docs.

2023-01-26 10:39 UTC, niegowski commented on packages/ckeditor5-media-embed/src/mediaembedui.ts
> +			form.urlInputView.bind( 'isEnabled' ).to( command, 'isEnabled' );
Ok I checked it and it looks like it was invalid before (probably while we were introducing labeled fields).

2023-01-27 13:12 UTC, mremiszewski commented on packages/ckeditor5-media-embed/src/mediaembedediting.ts
> +		// eslint-disable-next-line @typescript-eslint/consistent-type-assertions
I forgot to remove this line.

2023-02-10 13:26 UTC, arkflpc requested changes

2023-02-10 13:26 UTC, arkflpc commented on packages/ckeditor5-media-embed/src/mediaembed.ts
> +	interface EditorConfig {
Move this declaration and config-related interfaces to `mediaembedconfig.ts`

2023-02-10 13:26 UTC, arkflpc commented on packages/ckeditor5-media-embed/src/mediaembed.ts
> +	removeProviders: Array<string>;
I think it should be nullable.

2023-02-10 13:26 UTC, arkflpc commented on packages/ckeditor5-media-embed/src/mediaembedediting.ts
> +	interface CommandsMap {
Move it to `mediaembedcommand.ts`.

2023-02-10 13:26 UTC, arkflpc commented on packages/ckeditor5-media-embed/src/mediaembedtoolbar.ts
> +	interface MediaEmbedConfig {
Merge this with `MediaEmbedConfig` declared in `mediaembedconfig.ts`.

2023-02-10 13:26 UTC, arkflpc commented on packages/ckeditor5-media-embed/src/mediaregistry.ts
> +	 */
```suggestion
	 */
```

2023-02-10 13:26 UTC, arkflpc commented on packages/ckeditor5-media-embed/src/ui/mediaformview.ts
> +	 * @readonly
Unnecessary.

2023-02-10 13:26 UTC, arkflpc commented on packages/ckeditor5-media-embed/src/ui/mediaformview.ts
> +	 * @readonly
Unnecessary.

2023-02-10 13:26 UTC, arkflpc commented on packages/ckeditor5-media-embed/src/ui/mediaformview.ts
> + * @eventName submit
`eventName` should be attached to a type describing this event. It seems not used in this code anyway.

2023-02-10 13:26 UTC, arkflpc commented on packages/ckeditor5-media-embed/src/ui/mediaformview.ts
> + * @eventName cancel
`eventName` should be attached to a type describing this event. It seems not used in this code anyway.

2023-02-15 10:42 UTC, arkflpc approved these changes

2023-02-15 12:22 UTC, merged