Adding emojis section to special characters.
ckeditor/ckeditor5 pull request #13349
Opened 2023-01-27 12:30 UTC by godai78

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Other: adding emojis set to the special characters feature. Closes #13348

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-01-27 12:54 UTC, godai78 commented
Follow-up: update the \[special characters\](https://ckeditor.com/docs/ckeditor5/latest/features/special-characters.html) guide with a new example other than emojis.

2023-01-27 12:58 UTC, pomek requested changes
As mentioned. Also, we should rewrite [the documentation](https://ckeditor.com/docs/ckeditor5/latest/features/special-characters.html#adding-a-new-category) in the PR to avoid having two "Emoji" plugins.

2023-01-27 12:58 UTC, pomek commented on packages/ckeditor5-special-characters/src/specialcharactersemojis.js
> + * @module special-characters/specialcharactersarrows
```suggestion
 * @module special-characters/specialcharactersemojis
```

2023-01-27 13:03 UTC, godai78 commented on packages/ckeditor5-special-characters/src/specialcharactersemojis.js
> +			{ title: 'smiley face', character: '😊' },
I have never encountered translated emoji titles. Quick additional research shows no confirmed case of an app using translated emoji titles, at least for Poland.

2023-01-27 13:42 UTC, pomek reviewed
The code looks good. Now we need to update the documentation.

2023-01-27 19:10 UTC, pomek commented on packages/ckeditor5-special-characters/docs/features/special-characters.md
>  	], { label: 'Emoticons' } );
This should be renamed to `Borders` instead of `Emoticons`

2023-01-30 12:33 UTC, apadol-cksource commented
The change may be in conflict with plugins developed by the community in terms of UX, for instance, [https://www.npmjs.com/package/@phudak/ckeditor5-emoji](https://www.npmjs.com/package/@phudak/ckeditor5-emoji). Let's wait with merging it until we discuss the general approach to emojis. cc @Reinmar

2023-09-05 05:18 UTC, closed without merging