Added script for collecting svg icons
ckeditor/ckeditor5 pull request #13357
Opened 2023-01-30 12:29 UTC by przemyslaw-zan

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Other: Added script for collecting svg icons.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-01-30 14:51 UTC, pomek commented
@godai78, could you verify we understood the goals? Instruction on what to do with this script, you can find the issue.

2023-02-02 11:48 UTC, godai78 commented
We like it and we want it. Internal so far, but we want to revisit the idea and maybe make it public in the future as an UI creation aid.  
  
You can go on and merge it now. Can we have this available as a static page somewhere?

2023-02-02 13:28 UTC, pomek commented
> Can we have this available as a static page somewhere?

So far, it will be available only locally. I would not spend much time publishing it. If I understood correctly, we would add it somewhere in the documentation.

2023-02-02 13:44 UTC, godai78 commented
Actually, we need it more in Notion now, than the docs themselves.

2023-02-02 21:02 UTC, pomek requested changes
As mentioned, there are a few visual changes and some changes in the code (formatting + naming).

2023-02-02 21:02 UTC, pomek commented on scripts/collect-svg-icons.js
> +		'			img { max-height: 20px; }',
```suggestion
		'			* { box-sizing: border-box; }',
		'			body { font-family: Arial; }',
		'			table { border-collapse: collapse; margin: auto; margin-bottom: 25vh; }',
		'			thead tr:first-child th { padding-top: 20px; font-size: 150% }',
		'			tbody tr:nth-child(odd) td {background: #e5e5e5;}',
		'			td { border: 1px solid black; padding: 2px; }',
		'			img { max-height: 20px; }',
```

<img width="867" alt="image" src="https://user-images.githubusercontent.com/2270764/216448260-f5f83210-6514-4dc6-8753-53c69cbfe62b.png">

2023-02-06 13:50 UTC, pomek approved these changes
LGTM.

2023-02-06 13:51 UTC, merged