Updating missing info in feature guides.
ckeditor/ckeditor5 pull request #13421
Opened 2023-02-07 11:03 UTC by godai78

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Docs: Updating missing info in feature guides. Closes cksource/ckeditor5-internal#2655

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-02-07 16:14 UTC, apadol-cksource requested changes

2023-02-07 16:14 UTC, apadol-cksource commented on packages/ckeditor5-upload/docs/features/simple-upload-adapter.md
> +	This feature is not available in any of {@link installation/getting-started/predefined-builds#available-builds official editor builds}.  See the [installation](#installation) section to learn how to
Let's use "predefined builds" everywhere.

2023-02-08 06:15 UTC, godai78 commented on packages/ckeditor5-markdown-gfm/docs/features/markdown.md
> +	This feature is not available in any of {@link installation/getting-started/predefined-builds#available-builds official editor builds}.  See the [installation](#installation) section to learn how to
Not really, this info was duplicated from lead-in as an infobox, and hence was removed. It is not available again in the demo section.

2023-02-08 06:15 UTC, godai78 commented on packages/ckeditor5-style/docs/features/style.md
> +	This feature is not available in any of {@link installation/getting-started/predefined-builds#available-builds official editor builds}.  See the [installation](#installation) section to learn how to
Fixed in commit.

2023-02-08 09:02 UTC, apadol-cksource approved these changes
LGTM

2023-02-08 09:09 UTC, merged