Rewrite `ckeditor5-style` to TypeScript
ckeditor/ckeditor5 pull request #13461
Opened 2023-02-14 12:12 UTC by filipsobol

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Other (style): Rewrite `ckeditor5-style` to TypeScript. Closes #13032.

2023-02-16 12:09 UTC, filipsobol commented on packages/ckeditor5-clipboard/package.json
> +    "lodash-es": "^4.17.15"
This is the only package using `.11` while all others use `.15`

2023-02-16 12:27 UTC, arkflpc requested changes

2023-02-16 12:27 UTC, arkflpc commented on packages/ckeditor5-html-support/src/generalhtmlsupport.ts
> +	public addModelHtmlClass( viewElementName: string, className: ArrayOrItem<string>, selectable: LimitedSelectable ): void {
Make it internal. I know it's used outside this package, but it shouldn't be used by anyone (`ckeditor5-style` is an exception).

2023-02-16 12:27 UTC, arkflpc commented on packages/ckeditor5-html-support/src/generalhtmlsupport.ts
> +	public removeModelHtmlClass( viewElementName: string, className: ArrayOrItem<string>, selectable: LimitedSelectable ): void {
Make it internal. I know it's used outside this package, but it shouldn't be used by anyone (`ckeditor5-style` is an exception).

2023-02-16 12:27 UTC, arkflpc commented on packages/ckeditor5-style/src/style.ts
> + */
```suggestion
 */
```

2023-02-16 12:27 UTC, arkflpc commented on packages/ckeditor5-style/src/styleconfig.ts
> +  definitions: Array<StyleDefinition>;
```suggestion
  definitions?: Array<StyleDefinition>;
```

2023-02-16 12:27 UTC, arkflpc commented on packages/ckeditor5-style/src/styleconfig.ts
> +export type StyleDefinition = {
```suggestion
export interface StyleDefinition {
```

2023-02-20 14:08 UTC, arkflpc approved these changes

2023-02-21 09:27 UTC, merged