Docs: groundworks.
ckeditor/ckeditor5 pull request #13557
Opened 2023-02-27 08:15 UTC by godai78

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: adding multi-root editor to predefined builds. Closes #13536.

---

### Additional information

_Only proceed after_ #13532 _is merged._

2023-03-03 14:06 UTC, scofalik requested changes
One note regarding the image. IIRC, in the example that I prepared, the bottom boxes shoud have the same height.

2023-03-06 07:29 UTC, godai78 commented on docs/installation/getting-started/predefined-builds.md
> +<script src="https://cdn.ckeditor.com/ckeditor5/{@var ckeditor5-version}/multi-root/ckeditor.js"></script>
Ask Robert about it. I believe.

2023-03-06 07:52 UTC, godai78 commented on docs/installation/getting-started/predefined-builds.md
> +				<td style="text-align:center; width:70px">❌</td>
I checked it.

2023-03-06 09:05 UTC, godai78 commented on docs/installation/getting-started/predefined-builds.md
> +To try it out online, check the {@link examples/builds/inline-editor inline editor example}.
In commit.

2023-03-06 09:05 UTC, godai78 commented on docs/installation/getting-started/predefined-builds.md
> +<div id="editor"></div>
In commit.

2023-03-06 09:05 UTC, godai78 commented on docs/installation/getting-started/predefined-builds.md
> +Call the {@link module:editor-inline/inlineeditor~InlineEditor#create `InlineEditor.create()`} method.
In commit.

2023-03-06 09:05 UTC, godai78 commented on docs/installation/getting-started/predefined-builds.md
> +	InlineEditor
In commit.

2023-03-06 09:05 UTC, godai78 commented on packages/ckeditor5-editor-multi-root/README.md
> +The multi-root editor build for CKEditor 5. Read more about the [multi-root editor build](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/predefined-builds.html#multi-root-edi
In commit.

2023-03-10 12:36 UTC, godai78 commented
The recent push concerns cksource/ckeditor5-internal#2797

2023-03-10 14:48 UTC, merged