Docs: Add UI components article.
ckeditor/ckeditor5 pull request #13597
Opened 2023-03-02 15:16 UTC by gorzelinski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: Add UI components article. Closes https://github.com/cksource/ckeditor5-internal/issues/1898.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-03-02 15:21 UTC, gorzelinski commented
The article is almost ready. I'm still working on details, but I wanted to show what I have so far.
<img width="1485" alt="Screenshot 2023-03-02 at 16 20 06" src="https://user-images.githubusercontent.com/26603574/222470886-3bf9221b-f9e7-4cdb-a49f-0e3505fbca77.png">

2023-03-06 08:52 UTC, apadol-cksource requested changes
Great work and a great asset for documentation. I'm requesting few minor changes and I'm reporting 2 issues which may be related to the code and not the docs. To be verified.

2023-03-06 08:52 UTC, apadol-cksource commented on docs/framework/architecture/ui-components.md
> +---
Please add `modified_at` to add a "new" label.

2023-03-06 09:18 UTC, gorzelinski commented on docs/framework/architecture/ui-components.md
> +To get a rounded button, add the `ck-rounded-corners` class.
I was wondering why it's not displayed either. But, the class is applied - rounded corners only have 2px.
<img width="1469" alt="Screenshot 2023-03-06 at 10 14 04" src="https://user-images.githubusercontent.com/26603574/223067673-eee02280-5660-4e60-834a-b7bb0cd4e3c5.png">

2023-03-06 09:19 UTC, gorzelinski commented on docs/framework/architecture/ui-components.md
> +{@snippet framework/ui/ui-button}
Yeah, it's a good idea.

2023-03-07 20:37 UTC, apadol-cksource approved these changes
LGTM

2023-03-08 09:01 UTC, merged