Fix image resize handle displaying NaN.
ckeditor/ckeditor5 pull request #13613
Opened 2023-03-06 08:40 UTC by mremiszewski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (image): Fix the image resize handle displaying NaN in some scenarios. Closes #10776.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-03-07 15:07 UTC, arkflpc requested changes

2023-03-07 15:07 UTC, arkflpc commented on packages/ckeditor5-widget/src/widgetresize/resizerstate.ts
> +	try {
Add empty lines before and after code blocks.

2023-03-07 15:07 UTC, arkflpc commented on packages/ckeditor5-widget/src/widgetresize/resizerstate.ts
> +	}
Add empty lines before and after code blocks.

2023-03-08 07:19 UTC, mremiszewski commented on packages/ckeditor5-widget/src/widgetresize/resizerstate.ts
> +		while ( isNaN( parentWidth ) ) {
Ad 1
IMO, current version has better readability
```
let parentWidth = sth(); // everything goes as usual

// error handling
try {
    ...code...
}
```

even if the line with `parentWidth` calculation is duplicated. If you insist I can change that.

Ad 2 
Eventually we'll go up to some root element, and return `0` with `catch` block, but I'll add some limit to not go too high

2023-03-13 12:42 UTC, arkflpc approved these changes

2023-03-13 12:42 UTC, merged