Docs: Add TypeScript option to the Integrating from source using Vite guide.
ckeditor/ckeditor5 pull request #13738
Opened 2023-03-23 08:59 UTC by gorzelinski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: Add TypeScript option to the Integrating from source using Vite guide. Closes https://github.com/cksource/ckeditor5-internal/issues/2970.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-03-23 09:02 UTC, gorzelinski commented
I manually changed package versions to `37.0.0-alpha.3` to create this guide. But, with the next release, that won't be necessary for the end user.

2023-03-28 12:17 UTC, apadol-cksource requested changes

2023-03-28 12:17 UTC, apadol-cksource commented on docs/installation/advanced/integrating-from-source-vite.md
> +If you scaffolded your project using a Vite template with TypeScript, add the `ckeditor.ts` file in the `src` folder. Then, modify the file by adding the following lines of code.
Same as in the webpack guide. Please add TypeScript and JavaScript headings to relevant code snippets.

2023-03-29 07:09 UTC, apadol-cksource approved these changes

2023-03-29 07:34 UTC, merged