Docs: Add TypeScript options in Vue integration.
ckeditor/ckeditor5 pull request #13801
Opened 2023-03-31 11:43 UTC by gorzelinski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: Add TypeScript options in Vue integration. Closes https://github.com/cksource/ckeditor5-internal/issues/2991.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-03-31 11:46 UTC, gorzelinski commented
I need to mention a few key points.
- Similarly to previous integrations, I manually used the `37.0.0-alpha.3` CKEditor plugin versions.
- I manually used the `5.0.0-alpha.1` of the `ckeditor5-vue` package.
- Vue CLI and `create-vue` are based on interactive project scaffolding. So, I added Vue CLI and `create-vue` options as code snippets. They don't have any extensions because the coloring for the bash extension looked strange. I didn't see many screenshots in the documentation, so I stuck to snippets. But I can change them into screenshots.
- Probably there is no way to integrate Vue 2 with TypeScript. The integration is legacy, and the required Vue package doesn't have TypeScript declarations. I could use some hacks, but that doesn't make much sense. However, I unified the guide with the Vue 3 integration and added some missing steps.

2023-04-03 14:16 UTC, apadol-cksource requested changes

2023-04-03 14:16 UTC, apadol-cksource commented on docs/installation/frameworks/vuejs-v3.md
> +```
Same as with `create-vue`. Let's avoid pasting the interface we do not control.

2023-04-03 23:49 UTC, apadol-cksource requested changes
Also please chnage http://localhost:8080/ckeditor5/36.0.1/installation/frameworks/vuejs-v3.html#using-the-editor-from-source to `installing plugins and configuration`

2023-04-04 07:50 UTC, apadol-cksource approved these changes

2023-04-05 12:33 UTC, merged