Discovery: Implement focus handling for color picker
ckeditor/ckeditor5 pull request #13819
Opened 2023-04-04 07:57 UTC by illia-stv

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Feature: Discovery: Implement focus handling for color picker. Closes https://github.com/cksource/ckeditor5-internal/issues/2973

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-04-04 15:40 UTC, Dumluregn requested changes
PR works, and it also closes another issue (keyboard handling), so good job :+1: Let's polish it a bit. Besides a couple of small refactors, I miss the integration unit test for focus cycler - meaning that consecutively pressing `tab` and `shift+tab` we move to the expected parts of the component. So the logic in tests should be:  
1) focus element X (e.g. last document color tile)

2) press `tab`

3) check if the element Y (here - first color picker slider) is focused.

etc. for other components. It's already tested partially [here](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-font/tests/ui/colortableview.js#L174-L242), but without the color picker parts (as `appendColorPicker()` is not called in the test), so let's enhance this test suite.

2023-04-04 15:40 UTC, Dumluregn commented on packages/ckeditor5-font/tests/ui/colortableview.js
> +		} );
Putting this test inside `describe( 'updateSelectedColors() with document colors', ()` _`=>`_ `{` block seems weird, it should rather be in the `describe( 'appendColorPicker()', ()` _`=>`_ `{` one.

2023-04-04 15:43 UTC, Dumluregn commented
One more remark - let's add a clearer indication that slider is focused. We discussed it on Slack and this is the option we want to go with - [https://cksource.slack.com/archives/C014DN0KB1S/p1680611929301089?thread_ts=1680608490.373359&cid=C014DN0KB1S,](https://cksource.slack.com/archives/C014DN0KB1S/p1680611929301089?thread_ts=1680608490.373359&cid=C014DN0KB1S,) so please apply this style on the focused slider.

2023-04-05 13:32 UTC, illia-stv commented on packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts
> +		const sliders = colorPickersChildren.filter( item => item.tagName === 'DIV' );
I thought about this solution but unfortunately in our HTMLElement types there is no **#role** property, so I decided to filter by div's I think its safe, becouse we freezed package version of color picker library, so nothing will be changed there.  
![image](https://user-images.githubusercontent.com/47000454/230095976-e34b8767-1a41-4153-b6a3-116a6968cb1e.png)

2023-04-06 10:13 UTC, illia-stv commented
> One more remark - let's add a clearer indication that slider is focused. We discussed it on Slack and this is the option we want to go with - https://cksource.slack.com/archives/C014DN0KB1S/p1680611929301089?thread_ts=1680608490.373359&cid=C014DN0KB1S, so please apply this style on the focused slider.

It's a little bit tricky to style it due vanilla-colorful uses shadow dom under the hood. Let's move it to followup: https://github.com/cksource/ckeditor5-internal/issues/3050

2023-04-06 12:12 UTC, pszczesniak commented on packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts
> +		const sliders = colorPickersChildren.filter( item => item.tagName === 'DIV' );
Hmmm :thinking: looks fine in my `VSCode` - try one more time, do `yarn reinstall` or reopen the `VSCode`.  
 
<img width="772" alt="Screenshot 2023-04-06 at 14 09 04" src="https://user-images.githubusercontent.com/7074833/230375225-baeee2ae-e5ed-4828-bd05-9ba49714ec95.png">

2023-04-06 12:32 UTC, pszczesniak commented
I've push a [small update](https://github.com/ckeditor/ckeditor5/commit/702ae5401bbaa79daea9c9add3ca956ec4ab7fef) of how messages that need localization should be passed, based on [documentation](https://ckeditor.com/docs/ckeditor5/latest/framework/deep-dive/ui/localization.html#writing-a-localizable-ui).

2023-04-07 07:08 UTC, pszczesniak commented
Followup cksource/ckeditor5-internal#3065

2023-04-07 07:47 UTC, pszczesniak requested changes
I'm waiting for fixes that were reported by @Dumluregn and marked by You as resolved to look at it one more time.

2023-04-07 08:44 UTC, pszczesniak commented on packages/ckeditor5-font/src/ui/colortableview.ts
> +	private _focusColorPickersElements() {
Missing API docs and `type` of what this function returns.

2023-04-07 08:44 UTC, pszczesniak commented on packages/ckeditor5-font/src/ui/colortableview.ts
> +	private _stopPropagationOnArrowsKeys() {
Missing API docs and `type` of what this function returns.

2023-04-07 09:22 UTC, pszczesniak commented
CI is failing - some tests are not passing.

2023-04-11 07:59 UTC, pszczesniak approved these changes
LGTM :+1:

2023-04-11 08:50 UTC, mlewand commented
There's a unit test that is skipped because main branch doesn't have the changes of this PR: [https://github.com/ckeditor/ckeditor5/blob/3efbea82164a77f387fd614486a01eed24a70a18/packages/ckeditor5-ui/tests/colorpicker/colorpickerview.js#L66](https://github.com/ckeditor/ckeditor5/blob/3efbea82164a77f387fd614486a01eed24a70a18/packages/ckeditor5-ui/tests/colorpicker/colorpickerview.js#L66)

Please remove the `skip` in your PR - this should give a full CC.

(more in https://github.com/ckeditor/ckeditor5/pull/13820#issuecomment-1502930260)

2023-04-13 08:56 UTC, illia-stv commented
> There's a unit test that is skipped because main branch doesn't have the changes of this PR:
> 
> https://github.com/ckeditor/ckeditor5/blob/3efbea82164a77f387fd614486a01eed24a70a18/packages/ckeditor5-ui/tests/colorpicker/colorpickerview.js#L66
> 
> Please remove the `skip` in your PR - this should give a full CC.
> 
> (more in [#13820 (comment)](https://github.com/ckeditor/ckeditor5/pull/13820#issuecomment-1502930260))

After Piotrek's last merge, this **skip** was magically removed, look: https://github.com/ckeditor/ckeditor5/blob/4896e4d9c4eac89c95f94dd3deb1c42e9e83db7f/packages/ckeditor5-ui/tests/colorpicker/colorpickerview.js#L66

2023-04-13 10:12 UTC, merged