`getSelectedBlocks()` should ignore blocks where no content is selected
ckeditor/ckeditor5 pull request #13822
Opened 2023-04-04 13:16 UTC by filipsobol

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (engine): `Selection#getSelectedBlocks()` should ignore trailing blocks where no content is selected. The selection of such blocks is not visible to the content author and is usually there unintentionally. Closes #11585.

2023-04-05 08:23 UTC, Reinmar commented on packages/ckeditor5-engine/src/model/selection.ts
> +	 * <paragraph>]c</paragraph> // This block will not be returned
My OCD: This comment start from an upper case letter, while later on the same comment (different function) starts with a lower case :D

2023-04-05 08:24 UTC, Reinmar commented on packages/ckeditor5-engine/src/model/selection.ts
> +	 * // Selection ends and the beginning of the last block
Upper case -> period at the end. Think about this as a sentence.

2023-04-05 08:26 UTC, Reinmar commented
> Fix (engine): selection should ignore blocks where no content is selected. Closes to #11585.

Corrected:

> Fix (engine): `Selection#getSelectedBlocks()` should ignore trailing blocks where no content is selected. The selection of such blocks is not visible to the content author and is usually there unintentionally. Closes #11585.

2023-04-05 08:26 UTC, filipsobol commented on packages/ckeditor5-engine/src/model/selection.ts
> + * <paragraph>a[</paragraph> // this block will not be returned
```suggestion
 * <paragraph>a[</paragraph> // This block will not be returned
```

2023-04-05 08:26 UTC, filipsobol commented on packages/ckeditor5-engine/src/model/selection.ts
> + * <paragraph>a[]</paragraph> // this block will be returned
```suggestion
 * <paragraph>a[]</paragraph> // This block will be returned
```

2023-04-05 13:01 UTC, arkflpc requested changes

2023-04-06 10:50 UTC, filipsobol commented on packages/ckeditor5-engine/tests/model/selection.js
> +		describe( '#11585', () => {
Done ✔️

2023-04-11 06:18 UTC, merged