Docs: Add a clear indication that integrations work with TypeScript.
ckeditor/ckeditor5 pull request #13900
Opened 2023-04-18 07:09 UTC by gorzelinski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: Add a clear indication that integrations work with TypeScript. Closes https://github.com/cksource/ckeditor5-internal/issues/3125.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-04-18 09:23 UTC, apadol-cksource requested changes

2023-04-18 09:23 UTC, apadol-cksource commented on docs/installation/frameworks/angular.md
> +<info-box warning>
Please move the infobox above the table.

2023-04-18 09:23 UTC, apadol-cksource commented on docs/installation/frameworks/angular.md
> +	Starting with the v37.0.0 release, CKEditor 5 has built-in type definitions. Similarly, starting from the 6.0.0 version, the `@ckeditor/ckeditor5-angular` package also supports TypeScript.
```suggestion
Starting from version 6.0.0, you can use native type definitions provided by CKEditor 5. Check details about TypeScript support (link to general guide )
```

2023-04-18 12:24 UTC, gorzelinski commented on docs/installation/working-with-typescript.md
> +Starting with the v37.0.0 release, CKEditor 5 has built-in type definitions. Our official integrations for {@link installation/frameworks/angular Angular}, {@link installation/frameworks/react React}
I haven't thought about it, but it's a good idea. Now it looks better.

2023-04-19 18:41 UTC, apadol-cksource approved these changes

2023-04-20 06:23 UTC, merged