Ck/13777 add styles to table
ckeditor/ckeditor5 pull request #13937
Opened 2023-04-20 19:27 UTC by mremiszewski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Feature: Add custom styling support for `td`, `th`, `caption` and `figcaption` elements. Closes #13777.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-04-28 08:54 UTC, arkflpc requested changes

2023-04-28 08:54 UTC, arkflpc commented on packages/ckeditor5-style/src/styleutils.ts
> +	*/
internal?

2023-04-28 08:54 UTC, arkflpc commented on packages/ckeditor5-style/src/integrations/table.ts
> +/**
Module declaration should be before imports.

2023-04-28 09:19 UTC, arkflpc approved these changes

2023-04-28 09:41 UTC, merged

2023-04-30 14:26 UTC, wimleers commented
Hurray!