Docs: Unify imports in the documentation.
ckeditor/ckeditor5 pull request #13977
Opened 2023-04-25 12:25 UTC by gorzelinski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: Unify imports in the documentation. Closes https://github.com/cksource/ckeditor5-internal/issues/3117.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-04-26 12:42 UTC, gorzelinski commented
You can shorten and change most of the imports from default to named. But not all - some of them will not work after the change. As I was working on this issue, I found some exceptions:

* Editor builds e.g: `import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document/src/ckeditor';`
* Base classes e.g: `import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';`
* UI element e.g: `import ToolbarLineBreakView from '@ckeditor/ckeditor5-ui/src/toolbar/toolbarlinebreakview';`
* Util functions like: `import { getData } from '@ckeditor/ckeditor5-engine/src/dev-utils/model';`

Also, I didn't change some imports on purpose.

* I didn't change them retrospectively in files like `update-to-x.md` or changelog.
* I didn't change the imports in the dos and don'ts sections like working with typescript.
* I didn't change them either in the code style guide.

Of course, considering the number of changes, it's possible I missed something. But keep the above list in mind.

2023-05-10 23:44 UTC, apadol-cksource requested changes

2023-05-10 23:44 UTC, apadol-cksource commented on docs/installation/plugins/installing-plugins.md
>  import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
```suggestion
import { ClassicEditor } from '@ckeditor/ckeditor5-editor-classic';
```

2023-05-10 23:44 UTC, apadol-cksource commented on docs/installation/plugins/installing-plugins.md
>  export default class ClassicEditor extends ClassicEditorBase {}
export default class CustomEditor extends ClassicEditor {}

2023-05-10 23:44 UTC, apadol-cksource commented on docs/_snippets/framework/abbreviation-level-1.js
> +import { ClassicEditor } from '@ckeditor/ckeditor5-editor-classic';
let's keep the editor base first in the list. It applies to all examples. It is extended with the plugins so keeping it in the first place is more intuitive.

2023-05-11 21:43 UTC, apadol-cksource approved these changes
LGTM

2023-05-15 11:32 UTC, merged