Better handling of Ctrl+a in input in dropdown views
ckeditor/ckeditor5 pull request #13990
Opened 2023-04-27 11:23 UTC by mmotyczynska

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (ui): Select all (Ctrl+A) should now be enabled by default in input field placed in dropdown panel. Closes #13982.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-05-05 09:10 UTC, Dumluregn approved these changes

2023-05-05 09:27 UTC, Dumluregn requested changes
It works, but perhaps we can do it simpler :thinking: Since everything regarding `selectstart` happens in the same file, maybe we could edit the original listener instead of adding the new one (that requires the whole `render()` method).

I briefly PoCed it like this:

```
on: {
	// Drag and drop in the panel should not break the selection in the editor.
	// https://github.com/ckeditor/ckeditor5-ui/issues/228
	selectstart: bind.to( evt => {
		if ( ( evt.target as HTMLElement ).tagName.toLocaleLowerCase() === 'input' ) {
			return;
		}

		evt.preventDefault();
	} )
}
```

and it seems to work for me - could you verify it and adjust tests if needed?

2023-05-05 16:46 UTC, mmotyczynska commented
It works for me too and looks much simpler, thanks. I adjusted the tests.

2023-05-08 11:57 UTC, Dumluregn approved these changes

2023-05-08 12:32 UTC, merged