Added support for updating the release date references in CKEditor 5
ckeditor/ckeditor5 pull request #14032
Opened 2023-05-04 10:46 UTC by psmyrek

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Internal: Added support for updating the release date references in CKEditor 5. Closes #13972.

---

### Additional information

Notes:
- Removed the ability to make a commit. In the new release process a commit will be done at the end.
- Now, this script exports a function to make it possible to use it in the new release process.

2023-05-05 11:55 UTC, pomek reviewed
Would you like to integrate the spinner/counter into this script?

2023-05-05 11:56 UTC, pomek commented
One more point – perhaps we can integrate this script into the release process? I mean, execute the function in `scripts/release/prepare-packages.js`.

2023-05-05 13:01 UTC, psmyrek commented
Spinner integration seems unnecessary, because the script will execute very quickly and no one will even notice the spinner. The spinner would only blink for a short while.

But I integrated the script with the release process.

2023-05-08 09:37 UTC, przemyslaw-zan requested changes
LGTM, with one minor request.

2023-05-08 09:37 UTC, przemyslaw-zan commented on scripts/release/update-version-references.js
> +		const absolutePath = path.join( ROOT_DIRECTORY, file ).split( path.sep ).join( path.posix.sep );
As discussed recently, we should drop manual path normalization in favor of `upath` package.

2023-05-08 10:16 UTC, martnpaneq commented on scripts/release/update-version-references.js
> +		// TODO: Add file containing the release date.
Could we please not merge `// TODO` comments? It's likely that we'll forget it anyway. If it has to be done as part of some task, please add it to ZenHub.

2023-05-08 10:16 UTC, martnpaneq commented on scripts/release/update-version-references.js
> +// TODO: Not sure if the date format is OK.
Please remove `// TODO` before merging :)

2023-05-08 13:27 UTC, pomek approved these changes
LGTM.

2023-05-08 13:34 UTC, martnpaneq approved these changes

2023-05-08 16:01 UTC, pomek commented
@przemyslaw-zan, both arguments are marked as required. It's an internal script… we do not verify input as we know who consumes it.

<img width="570" alt="image" src="https://user-images.githubusercontent.com/2270764/236872607-577906db-586b-4adf-b53d-9f9719975a87.png">

2023-05-09 06:41 UTC, merged