Integrate color picker to cell properties
ckeditor/ckeditor5 pull request #14275
Opened 2023-05-29 14:53 UTC by illia-stv

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Feature (table): Integrate color picker to cell properties. Closes # https://github.com/cksource/ckeditor5-internal/issues/2978.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-06-05 14:16 UTC, oleq requested changes
There's an unnecessary margin left underneath the picker if there's no input configured:

<img width="223" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/1099479/6a39c5a1-a799-431f-9093-6e6e3f04c30e">

We can address thus by switching that bottom margin to the top margin of the input (or labeled field, if you will) using `+` selector only when the input follows the picker.

2023-06-05 14:16 UTC, oleq commented on packages/ckeditor5-table/src/tableproperties/ui/tablepropertiesview.ts
> +	 */
This is a whole config, not just the format.

2023-06-05 14:16 UTC, oleq commented on packages/ckeditor5-table/src/ui/colorinputview.ts
> +		} );
Are you sure this logic is covered in tests?

2023-06-05 14:16 UTC, oleq commented on packages/ckeditor5-table/src/ui/colorinputview.ts
> +		const colorGrid = new ColorTableView( locale, {
`ColorInputView` tests don't mention `ColorTableView`. We need more tests.

2023-06-05 14:16 UTC, oleq commented on packages/ckeditor5-table/src/utils/ui/table-properties.ts
> +			colorPickerConfig: options.colorPickerConfig
We need tests for `getLabeledColorInputCreator()` to check whether this config is accepted and actually passed down to the `ColorInputView`.

2023-06-05 14:16 UTC, oleq commented on packages/ckeditor5-table/src/tableconfig.ts
> +	colorPicker?: false | ColorPickerConfig;
I think we should mention this config somewhere in the doclets of `TableConfig` (`tableProperties?: TablePropertiesConfig;`)

2023-06-05 14:16 UTC, oleq commented on packages/ckeditor5-table/src/tableconfig.ts
> +	colorPicker?: false | ColorPickerConfig;
I think we should mention this config somewhere in the doclets of `TableConfig` (`tableCellProperties?: TableCellPropertiesConfig;`)

2023-06-05 14:16 UTC, oleq commented on packages/ckeditor5-font/src/ui/colorui.ts
> +				}
Do we have tests for this behavior?

2023-06-05 14:16 UTC, oleq commented on packages/ckeditor5-font/tests/ui/colortableview.js
>  	describe( 'disabled document colors section', () => {
What made you leave these tests behind in ckeditor5-font? Shouldn't they land in ckeditor5-ui?

2023-06-05 14:16 UTC, oleq commented on packages/ckeditor5-font/tests/ui/colortableview.js
>  describe( 'ColorTableView', () => {
Why are `ColorTableView` tests left behind in ckeditor5-font?

2023-06-13 13:19 UTC, oleq requested changes
Almost there 🙂

2023-06-13 13:21 UTC, oleq commented on packages/ckeditor5-ui/src/colorpicker/colorpickerview.ts
> -	*/
I tried to understand these docs but it appears they reference some non-existing methods or events. Could you please address this one?

2023-06-13 14:18 UTC, oleq commented
I also noticed this bug:

![2023-06-13 16 16 40](https://github.com/ckeditor/ckeditor5/assets/1099479/44861789-dd71-42f0-b955-b7bd63db25d0)


We should revert the value the form has been opened with upon clicking "cancel". [ATM we revert to configured default or `''`.](https://github.com/ckeditor/ckeditor5/blob/e2b1efc84fdfa77de4e77ed18194ad5f318722b6/packages/ckeditor5-table/src/ui/colorinputview.ts#L339)

2023-06-13 14:22 UTC, oleq commented
Also, can you check if 

```diff
diff --git a/packages/ckeditor5-table/src/ui/colorinputview.ts b/packages/ckeditor5-table/src/ui/colorinputview.ts
index 4f230df2fd..252f97da39 100644
--- a/packages/ckeditor5-table/src/ui/colorinputview.ts
+++ b/packages/ckeditor5-table/src/ui/colorinputview.ts
@@ -16,7 +16,9 @@ import {
          ColorTableView,
          type ColorDefinition,
          type DropdownView,
-         type ColorPickerConfig
+         type ColorPickerConfig,
+         type ColorTableExecuteEvent,
+         type ColorTableCancelEvent
 } from 'ckeditor5/src/ui';
 
 import { FocusTracker, KeystrokeHandler, type Locale } from 'ckeditor5/src/utils';
@@ -320,7 +322,11 @@ export default class ColorInputView extends View {
 
                   colorGrid!.appendUI();
 
-                  colorGrid.on( 'execute', ( _, data ) => {
+                  colorGrid.on<ColorTableExecuteEvent>( 'execute', ( evt, data ) => {
+                           if ( !this.dropdownView.isOpen ) {
+                                    return;
+                           }
+
                            if ( data.source === 'saveButton' ) {
                                     this.dropdownView.isOpen = false;
                                     return;
@@ -335,7 +341,7 @@ export default class ColorInputView extends View {
                            }
                   } );
 
-                  colorGrid.on( 'cancel', () => {
+                  colorGrid.on<ColorTableCancelEvent>( 'cancel', () => {
                            this.value = this.options.defaultColorValue || '';
 
                            this.fire( 'input' );
@@ -343,7 +349,7 @@ export default class ColorInputView extends View {
                            this.dropdownView.isOpen = false;
                   } );
 
-                  // colorGrid.bind( 'selectedColor' ).to( this, 'value' );
+                  colorGrid.bind( 'selectedColor' ).to( this, 'value' );
 
                   return colorGrid;
          }
```

resolves the problem of the feedback loop? I see that some random tests are still failing after this change but I suspect they are failing because the dropdown was not open before they were run (now it must be open for the new value to be applied).

2023-06-14 14:18 UTC, illia-stv commented
> Also, can you check if
> 
> ```diff
> diff --git a/packages/ckeditor5-table/src/ui/colorinputview.ts b/packages/ckeditor5-table/src/ui/colorinputview.ts
> index 4f230df2fd..252f97da39 100644
> --- a/packages/ckeditor5-table/src/ui/colorinputview.ts
> +++ b/packages/ckeditor5-table/src/ui/colorinputview.ts
> @@ -16,7 +16,9 @@ import {
>           ColorTableView,
>           type ColorDefinition,
>           type DropdownView,
> -         type ColorPickerConfig
> +         type ColorPickerConfig,
> +         type ColorTableExecuteEvent,
> +         type ColorTableCancelEvent
>  } from 'ckeditor5/src/ui';
>  
>  import { FocusTracker, KeystrokeHandler, type Locale } from 'ckeditor5/src/utils';
> @@ -320,7 +322,11 @@ export default class ColorInputView extends View {
>  
>                    colorGrid!.appendUI();
>  
> -                  colorGrid.on( 'execute', ( _, data ) => {
> +                  colorGrid.on<ColorTableExecuteEvent>( 'execute', ( evt, data ) => {
> +                           if ( !this.dropdownView.isOpen ) {
> +                                    return;
> +                           }
> +
>                             if ( data.source === 'saveButton' ) {
>                                      this.dropdownView.isOpen = false;
>                                      return;
> @@ -335,7 +341,7 @@ export default class ColorInputView extends View {
>                             }
>                    } );
>  
> -                  colorGrid.on( 'cancel', () => {
> +                  colorGrid.on<ColorTableCancelEvent>( 'cancel', () => {
>                             this.value = this.options.defaultColorValue || '';
>  
>                             this.fire( 'input' );
> @@ -343,7 +349,7 @@ export default class ColorInputView extends View {
>                             this.dropdownView.isOpen = false;
>                    } );
>  
> -                  // colorGrid.bind( 'selectedColor' ).to( this, 'value' );
> +                  colorGrid.bind( 'selectedColor' ).to( this, 'value' );
>  
>                    return colorGrid;
>           }
> ```
> 
> resolves the problem of the feedback loop? I see that some random tests are still failing after this change but I suspect they are failing because the dropdown was not open before they were run (now it must be open for the new value to be applied).

@oleq yeah you right, if will add `dropdown.isOpened = true` major of tests will pass but there is one test which fail, this one: https://github.com/ckeditor/ckeditor5/blob/4a01f6abd01581ad315033b85172782c156049d5/packages/ckeditor5-table/tests/ui/colorinputview.js#L190-L209 . On "cancel" button pressing we revert our changes, for example we back to "#ffaaff", when this change is applied we still have dropdown opened then color picker listener will handle this change and will convert it to hsl. Similar case with out color grid, as I know user could define any format of this static grid, for example **hex**, but it still will convert to hsl due this feedback loop, because dropdown is still opened.

2023-06-18 01:13 UTC, Dumluregn requested changes
I'd really like to already merge this PR to the epic, but there are still some things that don't really make sense to create separate issues for (they are not bugs, just code improvements), and otherwise we'd only put them away for later (when it may be harder to fix them).

Additionally I'll create a few extra tickets for the further work. For now, just short descriptions for the reference (don't bother with them yet):

*   There's an empty undo step if you set the color in table color picker and click cancel buttons in both color picker and table properties.
*   Selected color is not propagated to the color table view (and color picker) - I guess because `// colorGrid.bind( 'selectedColor' ).to( this, 'value' );` caused some troubles.
*   More thorough docs review + docs for `hideInput` config property.
*   Possibly the guides updates.
*   Should `hideInput` really just hide the input? Shouldn't it stop its creation at all? (other name needed then).

2023-06-19 08:51 UTC, illia-stv commented on packages/ckeditor5-ui/src/colorpicker/utils.ts
> +
https://github.com/ckeditor/ckeditor5/pull/14275#discussion_r1218094257

2023-06-19 09:07 UTC, illia-stv commented on packages/ckeditor5-table/src/ui/colorinputview.ts
> +			this.fire( 'input' );
It just applies the color to property which was defined in **this.value**. It trigers this part of code:
https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-table/src/tablecellproperties/ui/tablecellpropertiesview.ts#L511-L513

2023-06-19 12:08 UTC, Dumluregn commented on packages/ckeditor5-ui/src/colorpicker/utils.ts
> +
Ok, so this is valid if we don't want to expose `hideInput` as a configurable property for the user. But maybe we could just do it? We'll discuss it later.

2023-06-19 14:34 UTC, Dumluregn approved these changes
I leave R+ for this PR but let's all be aware there are follow-ups we need to handle until it's the production ready code.

As you may notice, I changed the "Closes" section:

*   The original integration issue was changed to be an epic. This PR only handles part of the job. Therefore, I created #14412 which is meant to indicate the actual status. Epic stays open.
*   I decided this PR doesn't solve #14361. At least not in the way that was requested in [https://github.com/ckeditor/ckeditor5/issues/14361#issuecomment-1582211440.](https://github.com/ckeditor/ckeditor5/issues/14361#issuecomment-1582211440.) Here we've removed the `submit` button type, while it carries the semantic value. To solve #14361, we should restore `submit` type together with its proper handling. BTW, there are two more buttons in the table plugin ("save" buttons in table properties and table cell properties) that use this type, so [let's ensure they work as expected too](https://github.com/ckeditor/ckeditor5/issues/14361#issuecomment-1597299873).

As promised before, there will be follow-ups that I will add to the epic.

2023-06-19 14:35 UTC, merged