Docs: Consolidate guides for build customization.
ckeditor/ckeditor5 pull request #14631
Opened 2023-07-21 13:24 UTC by gorzelinski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: Consolidate guides for build customization. Closes https://github.com/cksource/ckeditor5-internal/issues/1868.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-07-21 13:59 UTC, gorzelinski commented
I must add some remarks here.

Adding any plugin to the build from the online builder causes a TypeScript error:
`Class static side 'typeof Editor' incorrectly extends base class static side 'typeof ClassicEditor'.`

There is a file with custom declarations in the build folder - `ckeditor.d.ts.`

```ts
```

The array with built-in plugins has a specific set of plugins.

2023-07-21 14:13 UTC, gorzelinski commented
I must add some remarks here.

Adding any plugin to the build from the online builder (like in the [guide](http://127.0.0.1:8080/ckeditor5/38.1.1/installation/getting-started/quick-start-other.html)) causes a TypeScript error:

`Class static side 'typeof Editor' incorrectly extends base class static side 'typeof ClassicEditor'.`

There is a file with custom declarations in the `build` folder - `ckeditor.d.ts`

```ts
declare class Editor extends ClassicEditor {
    static builtinPlugins: (typeof TextTransformation | typeof Autoformat | typeof Bold | typeof Italic | typeof BlockQuote | typeof CloudServices | typeof Essentials | typeof Paragraph | typeof Heading | typeof Image | typeof ImageCaption | typeof ImageStyle | typeof ImageToolbar | typeof ImageUpload | typeof Indent | typeof Link | typeof List | typeof MediaEmbed | typeof PasteFromOffice | typeof Table | typeof TableToolbar)[];
    static defaultConfig: {
        toolbar: {
            items: string[];
        };
        language: string;
        image: {
            toolbar: string[];
        };
        table: {
            contentToolbar: string[];
        };
    };
}
```

The array with built-in plugins seems to have a specific set of plugins. Trying to add anything seems to break the union type there. You can change the `.d.ts` file, but you'll get the same error. I'll be debugging this problem.

2023-07-25 09:19 UTC, apadol-cksource requested changes

2023-07-25 09:19 UTC, apadol-cksource commented on docs/installation/plugins/installing-plugins.md
> +## Adding a JavaScript plugin
In most cases, developers will use plugins provided by CKEditor and then the section will cause confusion. Let's move it to the end of the article.

2023-07-25 09:19 UTC, apadol-cksource commented on docs/installation/plugins/installing-plugins.md
> +The CKEditor is a TypeScript project, and all plugins also use TypeScript. However, there are ways to use JavaScript packages with the editor.
```suggestion
The CKEditor 5 is a TypeScript project, and all plugins provided by CKEditor 5 also use TypeScript. However, there are ways to use JavaScript packages with the editor.
```

2023-07-25 11:53 UTC, gorzelinski commented on docs/installation/plugins/installing-plugins.md
> +## Creating an editor base
I wasn't sure about this subheading either. Tbh, it was more of a placeholder. I'll change it.

2023-07-25 11:58 UTC, gorzelinski commented on docs/installation/plugins/installing-plugins.md
> +3. Display proper UI for the installed plugin to let users use it.
I forgot about plugins that don't have a UI - good point.

2023-07-26 10:31 UTC, apadol-cksource approved these changes

2023-07-26 11:35 UTC, merged