[PoC] to-do lists in document lists.
ckeditor/ckeditor5 pull request #14700
Opened 2023-07-31 17:49 UTC by niegowski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Type: Message. Closes #000.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-08-03 13:59 UTC, arkflpc commented on packages/ckeditor5-list/src/documentlist/utils/view.ts
> +	type: string,
I don't like it.

2023-08-03 13:59 UTC, arkflpc commented on packages/ckeditor5-list/src/todo.ts
> +export default class Todo extends Plugin {
Remember to name it properly.

2023-08-22 11:04 UTC, arkflpc approved these changes

2023-08-29 08:11 UTC, arkflpc commented on packages/ckeditor5-list/src/tododocumentlist/checktododocumentlistcommand.ts
> +		return selectedElements.every( element => !!element.getAttribute( attributeKey ) );
```suggestion
		return selectedElements.every( element => element.getAttribute( attributeKey ) );
```
I believe, the expected return type of the predicate is `unknown`.

2023-08-29 08:11 UTC, arkflpc commented on packages/ckeditor5-list/src/tododocumentlist/inputchangeobserver.ts
> +export default class InputChangeObserver extends DomEventObserver<'change'> {
Why such a generic class is in `tododocumentlist` instead of in `engine`?

2023-08-29 08:11 UTC, arkflpc commented on packages/ckeditor5-list/src/tododocumentlist/checktododocumentlistcommand.ts
> +const attributeKey = 'todoListChecked';
Be consistent with letter case. I.e. `ITEM_TOGGLE_KEYSTROKE` in other file is upper-case.

2023-08-29 08:11 UTC, arkflpc commented on packages/ckeditor5-list/src/documentlistproperties/documentlistpropertiesediting.ts
> -				const nodeIndent = node.getAttribute( 'listIndent' );
Is this logic not needed or moved somewhere? I don't see it.

2023-08-30 09:31 UTC, arkflpc requested changes

2023-08-30 09:31 UTC, arkflpc commented on packages/ckeditor5-list/src/tododocumentlist/inputchangeobserver.ts
> +export default class InputChangeObserver extends DomEventObserver<'change'> {
If it stays here, it should be narrowed to the TodoLists.

2023-09-19 12:01 UTC, charlttsie commented
@niegowski It seems like with Heading 1, the position of the checkbox is too high compared to how it looks with unordered and ordered document lists:
<img width="318" alt="checkbox-position-H1" src="https://github.com/ckeditor/ckeditor5/assets/132071257/1e04e416-e3f5-4a90-8a2a-fec19a5bb9a0">

It looks better with other heading levels:
<img width="333" alt="checkbox-position-h2" src="https://github.com/ckeditor/ckeditor5/assets/132071257/cd54017a-5680-4e20-bd48-afda24303314">
<img width="329" alt="checkbox-position-h3" src="https://github.com/ckeditor/ckeditor5/assets/132071257/7f201671-f594-4d79-bc6d-3279de835673">

2023-09-19 14:44 UTC, charlttsie commented
### Checkboxes next to code block items are not responsive

**Steps**
1. Add the Code block plugin to http://fake.ckeditor.com:8125/ckeditor5-list/tests/manual/todo-documentlist.html
2. Add a code block as a to-do list item
3. Try to check the checkbox

**Result**
The checkbox can't be checked:

https://github.com/ckeditor/ckeditor5/assets/132071257/35ae6f6d-f53f-46d6-81d4-75ce7beebf07

**Additional info**
Works good with other widgets (including images, tables, block quotes)

2023-09-20 06:08 UTC, charlttsie commented
### Switching to-do list on and off on an element affects checkboxes of the list items below 

**Steps**
1. Open http://fake.ckeditor.com:8125/ckeditor5-list/tests/manual/todo-documentlist.html
2. Add a couple of to-do list items and check the checkboxes for some of them
3. Place the caret in the first list item
4. Click the to-do list toolbar icon

**Result**
For a moment, checkboxes on unchecked list items get green highlight, while checked checkboxes lose the check mark:

https://github.com/ckeditor/ckeditor5/assets/132071257/d051b811-cb3c-43d9-9dc2-4b1577c5c2d2

**Additional info**
It's not reproducible with legacy to-do lists

2023-09-20 06:49 UTC, charlttsie commented
### Alignment of to-do document list items can't be changed 
**Steps**
1. Add the alignment plugin to http://fake.ckeditor.com:8125/ckeditor5-list/tests/manual/todo-documentlist.html and open the manual test
2. Add a list item
3. Try to change the item's alignment 

**Result** 
The position of the list item doesn't change:

https://github.com/ckeditor/ckeditor5/assets/132071257/43c7f627-1d7b-478c-aba6-8186cbc2842f

**Additional info**
Works good with other document list types and with legacy to-do lists

2023-09-21 09:08 UTC, charlttsie commented
@niegowski 
It will probably be a follow-up but one more thing is that Track Changes is not yet supported: 

https://github.com/ckeditor/ckeditor5/assets/132071257/80af9c8b-5c93-4987-b532-40f656ff10ae

2023-09-21 12:33 UTC, arkflpc requested changes

2023-09-21 12:33 UTC, arkflpc commented on packages/ckeditor5-list/src/tododocumentlist/tododocumentlistediting.ts
> +					... ( dataPipeline ?
```suggestion
					...( dataPipeline ?
```

2023-09-21 12:36 UTC, arkflpc approved these changes

2023-09-21 12:55 UTC, merged