Preview logic requires tweaking
ckeditor/ckeditor5 pull request #14983
Opened 2023-09-13 10:11 UTC by illia-stv

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (clipboard): improve displaying preview in "drag and drop". Closes #14968.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-09-13 13:55 UTC, niegowski requested changes

2023-09-14 11:27 UTC, filipsobol commented on packages/ckeditor5-clipboard/src/dragdropexperimental.ts
> +	Rect
Regular imports should go before `type` imports

2023-09-14 11:29 UTC, filipsobol commented on packages/ckeditor5-clipboard/src/dragdropexperimental.ts
> +		// If domTarget is inside editable root, browser display preview by own.
```suggestion
		// If domTarget is inside the editable root, browsers will display the preview correctly by themselves.
```

I think this reads better.

2023-09-14 11:31 UTC, filipsobol commented on packages/ckeditor5-clipboard/tests/dragdropexperimental.js
> +			domNode = !domTarget ? domConverter.mapViewToDom( viewElement ) : domTarget;
domNode = domTarget || domConverter.mapViewToDom( viewElement );

2023-09-14 11:31 UTC, filipsobol commented on packages/ckeditor5-clipboard/tests/dragdropexperimental.js
> +			domNode = !domTarget ? domConverter.mapViewToDom( viewElement ) : domTarget;
```suggestion
			domNode = domTarget || domConverter.mapViewToDom( viewElement );
```

2023-09-14 11:41 UTC, filipsobol commented on packages/ckeditor5-clipboard/tests/dragdropexperimental.js
> +			it( 'should show preview with custom implementation', () => {
It's not clear from the test names alone when the editor `should show preview with custom implementation` and when it `should show preview with browser implementation`. Please include information when one or the other is used, so it's not necessary to read the test details.

For example: `should show preview with custom implementation if [...]` and `should show preview with browser implementation if [...]`.

2023-09-14 11:43 UTC, filipsobol reviewed
I added few minor comments

2023-09-15 12:39 UTC, niegowski approved these changes

2023-09-15 12:40 UTC, merged