Enable block drag and drop by default
ckeditor/ckeditor5 pull request #15016
Opened 2023-09-18 09:02 UTC by illia-stv

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Feature( clipboard ): Enable block drag and drop by default. Closes #14734.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-09-19 12:52 UTC, arkflpc requested changes

2023-09-19 12:52 UTC, arkflpc commented on packages/ckeditor5-clipboard/src/clipboard.ts
> +import DragDropExperimental from './dragdropexperimental';
`DragDropExperimental` should replace old `DragDrop` plugin.

2023-09-25 10:38 UTC, niegowski requested changes
Missing code coverage.

2023-09-26 10:01 UTC, niegowski approved these changes

2023-09-26 10:34 UTC, merged