Fix(ckbox): Improve error handling.
ckeditor/ckeditor5 pull request #15124
Opened 2023-10-04 08:46 UTC by gorzelinski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix(ckbox): Improve error handling. Closes #13062.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-10-04 08:47 UTC, gorzelinski commented
The current implementation works, but I'm not sure about it. I considered some alternatives.

```ts
if ( !isLibraryLoaded ) {
    /**
     * The CKBox library is not loaded.
     * Follow the instructions provided in {@glink features/file-management/ckbox#installation the CKBox feature documentation}
     * to load the library properly.
     *
     * @error ckbox-library-not-loaded
     */
    logWarning( 'ckbox-library-not-loaded' );
    return;
}

if ( !hasConfiguration ) {
    /**
     * The configuration required by the ckbox plugin is missing.
     * Follow the instructions provided in {@glink features/file-management/ckbox#configuration the CKBox feature documentation}
     * to initialize the plugin properly.
     *
     * @error ckbox-config-not-found
     * @param {module:ckbox/ckboxconfig~CKBoxConfig} config Configuration of the ckbox.
     */
    logWarning( 'ckbox-config-not-found', editor );
    return;
}
```

The code logs warnings correctly, but it's not equivalent to the original code. Tests failed as expected, but I tested it anyway.

---

```ts
if ( !isLibraryLoaded ) {
    /**
     * The CKBox library is not loaded.
     * Follow the instructions provided in {@glink features/file-management/ckbox#installation the CKBox feature documentation}
     * to load the library properly.
     *
     * @error ckbox-library-not-loaded
     */
    logWarning( 'ckbox-library-not-loaded' );

    if ( !hasConfiguration ) {
        /**
         * The configuration required by the ckbox plugin is missing.
         * Follow the instructions provided in {@glink features/file-management/ckbox#configuration the CKBox feature documentation}
         * to initialize the plugin properly.
         *
         * @error ckbox-config-not-found
         * @param {module:ckbox/ckboxconfig~CKBoxConfig} config Configuration of the ckbox.
         */
        logWarning( 'ckbox-config-not-found', editor );
        return;
    }
}
```

The code is equivalent to the original. Tests pass. But there is an edge case - nested warning depends on the outer if.

---

```ts
if ( !isLibraryLoaded ) {
    /**
     * The CKBox library is not loaded.
     * Follow the instructions provided in {@glink features/file-management/ckbox#installation the CKBox feature documentation}
     * to load the library properly.
     *
     * @error ckbox-library-not-loaded
     */
    logWarning( 'ckbox-library-not-loaded' );
}

if ( !hasConfiguration ) {
    /**
     * The configuration required by the ckbox plugin is missing.
     * Follow the instructions provided in {@glink features/file-management/ckbox#configuration the CKBox feature documentation}
     * to initialize the plugin properly.
     *
     * @error ckbox-config-not-found
     * @param {module:ckbox/ckboxconfig~CKBoxConfig} config Configuration of the ckbox.
     */
    logWarning( 'ckbox-config-not-found', editor );
}

if( !hasConfiguration && !isLibraryLoaded) {
    return;
}
```

Committed implementation works. Warnings are displayed. Tests pass. But it looks a little redundant - I don't know if that's the most elegant solution.

2023-10-06 12:54 UTC, gorzelinski commented
The last commit fixed issues in CKBox unit tests. I also saw warnings in build unit tests. I guess that builds use CKBox. So, I need to handle them as well.

2023-10-10 13:05 UTC, gorzelinski commented
I don't know what to do with failing unit tests, tbh. Added warnings cause [CI to crash](https://app.circleci.com/pipelines/github/ckeditor/ckeditor5/968/workflows/b36fbdfd-4fae-4dc2-b60c-68d1aab2af41/jobs/4900). It's because the [builds per se](https://github.com/ckeditor/ckeditor5/blob/ck/13062/packages/ckeditor5-build-balloon/src/ckeditor.ts) have `ckbox` in the list of plugins but no configuration. I tried to mock the config in the [unit tests](https://github.com/ckeditor/ckeditor5/blob/ck/13062/packages/ckeditor5-build-balloon/tests/ckeditor.js) but without results. I'm not sure if that's the right solution in the first place. If I understand correctly, CKBox won't work without config, and our builds don't have one. I could delete the CKBox plugin from the list of plugins - that would solve the issue, but we probably don't want that. I could also add an example config in our builds, but I don't know if we have something like this. Fake config doesn't work. Or I'm missing something. Long story short, currently, I see two solutions:

1. Deleting CKBox from the builds.
2. Adding an example CKBox config to the builds.
3. ?

2023-10-11 12:19 UTC, gorzelinski commented
@pszczesniak found a token used in cloud services tests. In the end, I reused it here. It solved the above issue with the CI. However, our builds still don't have an example config. I don't know if we want to change that.

2023-10-12 12:32 UTC, arkflpc requested changes

2023-10-12 12:32 UTC, arkflpc commented on packages/ckeditor5-ckbox/tests/ckbox.js
> +		originalCKBox = window.CKBox;
Why?

2023-10-12 12:32 UTC, arkflpc commented on packages/ckeditor5-ckbox/tests/ckboxediting.js
> +			expect( console.warn.callCount ).to.equal( 1 );
It would be nice, to check the warning text as well. I.e. if it contains `ckbox-config-not-found`.

2023-10-12 12:32 UTC, arkflpc commented on packages/ckeditor5-ckbox/tests/ckboxediting.js
> +		expect( console.warn.callCount ).to.equal( 1 );
It would be nice, to check the warning text as well. I.e. if it contains `ckbox-library-not-loaded`.

2023-10-12 12:32 UTC, arkflpc commented
Let's wait for https://github.com/ckeditor/ckeditor5/issues/13062#issuecomment-1759497032 and https://github.com/ckeditor/ckeditor5/issues/13062#issuecomment-1759515299 to be addressed.

2023-10-12 14:50 UTC, pszczesniak requested changes

2023-10-12 14:50 UTC, pszczesniak commented on packages/ckeditor5-ckbox/src/ckboxediting.ts
> +			 * The configuration required by the ckbox plugin is missing.
```suggestion
			 * The configuration required by the CKBox plugin is missing.
```

2023-10-12 14:50 UTC, pszczesniak commented on packages/ckeditor5-ckbox/src/ckboxediting.ts
> +			 * @param {module:ckbox/ckboxconfig~CKBoxConfig} config Configuration of the ckbox.
```suggestion
			 * @param {module:ckbox/ckboxconfig~CKBoxConfig} config Configuration of the CKBox.
```

2024-11-11 23:53 UTC, closed without merging