Manual test with simple image
ckeditor/ckeditor5 pull request #15222
Opened 2023-10-23 16:04 UTC by niegowski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Internal (image): Added manual test with overridden image conversion to use only size attributes for images. Closes #15185.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-10-26 07:13 UTC, arkflpc requested changes

2023-10-26 07:13 UTC, arkflpc commented on packages/ckeditor5-image/tests/manual/simple-image.ts
> +	editor.editing.view.document.on( 'imageLoaded', ( evt, domEvent ) => {
You used event type in line 33. Why don't do that here.

2023-10-26 07:13 UTC, arkflpc commented on packages/ckeditor5-image/tests/manual/simple-image.ts
> +	.create( document.getElementById( 'editor' ), {
It does not compile for me. `getElementById` can return `null`.

2023-10-26 07:13 UTC, arkflpc commented on packages/ckeditor5-image/tests/manual/simple-image.ts
> +				const item = change.range.start.nodeAfter;
The lines below do not compile for me. `nodeAfter` can return null.

2023-10-26 07:13 UTC, arkflpc commented on packages/ckeditor5-image/tests/manual/simple-image.ts
> +		for ( const item of images ) {
In my IDE images are inferred as `never[]`, so the lines below do not compile.

2023-10-26 12:19 UTC, arkflpc approved these changes

2023-10-27 12:22 UTC, filipsobol approved these changes

2023-10-27 14:34 UTC, merged