Docs: adding CKBOx editing to demos
ckeditor/ckeditor5 pull request #15259
Opened 2023-10-27 07:31 UTC by godai78

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: adding CKBOx editing to demos. Closes https://github.com/ckeditor/ckeditor5/issues/15225

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-10-31 16:38 UTC, mmotyczynska requested changes
There are some questions and suggestions in the comments.

Besides that, I did not find the `Edit Image` button in the following features (I did not check all of them, but it turns out it is because of the missing image toolbar config or used Easy Image). I believe this will be covered in a follow-up ticket. But I am pasting the list here anyway for future reference:

- Autoformatting
- Automatic text transformation
- Autosave
- Basic text styles
- Block indentation
- Code blocks
- Content minimap
- Editor placeholder
- Find and replace
- Font family, size, and color
- Highlight
- General HTML Support
- HTML comment element
- Full page HTML
- Link
- To-do lists
- Media embed
- Mentions
- Paste plain text
- Read-only support
- Remove formatting
- Restricted editing
- Select all
- Show blocks
- Spelling, grammar, and punctuation checking
- Styles
- Text alignment
- Text part language
- Setting the UI language

And for the Images (I think some of them can be done in this ticket):

- Image text alternative
- Image captions
- Resizing images
- Responsive images
- Image styles
- Linking images
- Inserting images via URL (missing image toolbar)

2023-11-02 10:49 UTC, gorzelinski commented on docs/_snippets/features/toolbar-nested-label.js
> +		},
I tested it. If we want to keep the functionality of pasting images, it makes sense to leave the config.

2023-11-02 11:00 UTC, gorzelinski commented on packages/ckeditor5-table/docs/_snippets/features/table-basic.js
> +				'ckboxImageEdit'
It seems that no page is using this snippet. We probably don't need it.

2023-11-02 12:16 UTC, gorzelinski commented on packages/ckeditor5-word-count/docs/_snippets/features/build-word-count-source.js
> +			'ckboxImageEdit'
Yeah, these snippets have their configs. The config in the base snippet is probably redundant.

2023-11-03 15:06 UTC, mmotyczynska approved these changes
LGTM 👍

2023-11-03 15:13 UTC, merged

2023-11-06 10:59 UTC, godai78 commented
Actually I left out the image demos on purpose. They each highlight a single toolbar item, so throwing edit into each one seemed like a bad idea.