Implement processing state indicator.
ckeditor/ckeditor5 pull request #15317
Opened 2023-11-06 21:12 UTC by pszczesniak

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Internal(ckbox): Should show indicator while image is processing after editing. Closes https://github.com/cksource/ckeditor5-commercial/issues/5638.

---

### Additional information

TOKEN_URL = 'https://preview.ckbox.io/cke-workspaces-demo/?page=token'

☝️ This token endpoint should be used in manual test to test the CKBox Image Editor (getAsset wont throw any errors).

2023-11-10 14:59 UTC, arkflpc requested changes

2023-11-10 14:59 UTC, arkflpc commented on packages/ckeditor5-ckbox/tests/ckboximageedit/ckboximageeditcommand.js
> +				const clock = sinon.useFakeTimers();
Do we need `sinon.restore()`?

2023-11-10 15:49 UTC, pszczesniak commented on packages/ckeditor5-ckbox/tests/ckboximageedit/ckboximageeditcommand.js
> +				const clock = sinon.useFakeTimers();
Adresed in 7117b38

2023-11-13 11:32 UTC, arkflpc approved these changes

2023-11-13 11:33 UTC, merged