Using document title in tandem with drag and drop
ckeditor/ckeditor5 pull request #15523
Opened 2023-12-13 14:49 UTC by illia-stv

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (clipboard): Should not through errors while using drag and drop with document title. Closes #15306.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2023-12-15 08:01 UTC, Witoso commented on packages/ckeditor5-clipboard/tests/dragdrop.js
> +	function CustomTitle( editor ) {
Out of curiosity, why is this tested against `CustomTitle`, and not [Title](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/title.html) plugin?

2023-12-15 08:56 UTC, pszczesniak requested changes
After run the manual test `yarn manual -f heading` i get still the same error:

https://github.com/ckeditor/ckeditor5/assets/7074833/a0ef1029-42c5-4b42-b190-5ec5f1bbc156

2023-12-15 13:26 UTC, pszczesniak commented
One more thing i noticed, but his can be a follow-up for this (not allow to drop for example an image into `Title`):

https://github.com/ckeditor/ckeditor5/assets/7074833/22ab611d-6bed-4d63-9fd6-c93111b8614f

2023-12-18 08:16 UTC, pszczesniak approved these changes
LGTM - it does what it should :)

2023-12-19 09:23 UTC, arkflpc approved these changes

2023-12-19 09:33 UTC, merged