Docs: updating installation sections.
ckeditor/ckeditor5 pull request #16009
Opened 2024-03-11 13:44 UTC by godai78

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: updating installation sections. Closes cksource/ckeditor5-commercial#6076

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2024-03-12 11:54 UTC, gorzelinski requested changes
Most of the changes are probably done semi-automatically (I guess), and that's good. But some of the formatting is off because of that. I would change the formatting before merging.

2024-03-12 11:54 UTC, gorzelinski commented on packages/ckeditor5-typing/docs/features/text-transformation.md
> +	.then( /* ... */ );
```suggestion
.then( /* ... */ );
```

2024-03-12 11:54 UTC, gorzelinski commented on packages/ckeditor5-typing/docs/features/text-transformation.md
> +	.then( /* ... */ );
```suggestion
.then( /* ... */ );
```

2024-03-12 11:54 UTC, gorzelinski commented on packages/ckeditor5-typing/docs/features/text-transformation.md
> +	.then( /* ... */ );
```suggestion
.then( /* ... */ );
```

2024-03-12 11:54 UTC, gorzelinski commented on packages/ckeditor5-upload/docs/features/base64-upload-adapter.md
> +	.then( /* ... */ );
```suggestion
.then( /* ... */ );
```

2024-03-12 11:54 UTC, gorzelinski commented on packages/ckeditor5-upload/docs/features/simple-upload-adapter.md
> +	.then( /* ... */ );
```suggestion
.then( /* ... */ );
```

2024-03-12 11:54 UTC, gorzelinski commented on packages/ckeditor5-watchdog/docs/features/watchdog.md
> +import { ClassicEditor, Paragraph } from '@ckeditor/ckeditor5-paragraph';
```suggestion
import { ClassicEditor, Bold, EditorWatchdog, Essentials, Italic, Paragraph } from 'ckeditor5';
```

I guess something went wrong here after some mechanical changes. I also guess that EditorWatchdog will be available in the open-source package.

2024-03-12 11:54 UTC, gorzelinski commented on packages/ckeditor5-word-count/docs/features/word-count.md
>  		const wordCountWrapper = document.getElementById( 'word-count' );
```suggestion
.then( editor => {
	const wordCountPlugin = editor.plugins.get( 'WordCount' );
	const wordCountWrapper = document.getElementById( 'word-count' );
```

2024-03-12 11:54 UTC, gorzelinski commented on packages/ckeditor5-word-count/docs/features/word-count.md
> +	.then( /* ... */ );
```suggestion
.then( /* ... */ );
```

2024-03-12 12:05 UTC, godai78 commented on packages/ckeditor5-alignment/docs/features/text-alignment.md
> +	.then( /* ... */ );
It was done along the lines of accepted version from Notion...  
  
[https://www.notion.so/Implement-changes-to-basic-Features-guides-071c814c3dc447b49b3255f64da15875](https://www.notion.so/Implement-changes-to-basic-Features-guides-071c814c3dc447b49b3255f64da15875)  
  
Too bad the accepted version was not correct :D

2024-03-13 08:08 UTC, gorzelinski reviewed
I found some minor problems - mainly with some imports.

2024-03-13 08:08 UTC, gorzelinski commented on packages/ckeditor5-watchdog/docs/features/watchdog.md
> +import { ClassicEditor, EditorWatchdog } from '@ckeditor/ckeditor5-watchdog';
```suggestion

```

2024-03-13 08:08 UTC, gorzelinski commented on packages/ckeditor5-watchdog/docs/features/watchdog.md
>  import { ClassicEditor } from '@ckeditor/ckeditor5-editor-classic';
```suggestion

```

2024-03-13 08:08 UTC, gorzelinski commented on packages/ckeditor5-watchdog/docs/features/watchdog.md
> +import { ClassicEditor, EditorWatchdog } from '@ckeditor/ckeditor5-watchdog';
Those imports are no longer needed - everything is imported from the main open-source package.

2024-03-13 08:08 UTC, gorzelinski commented on packages/ckeditor5-word-count/docs/features/word-count.md
>  	} )
```suggestion
ClassicEditor.create( document.querySelector( '#editor' ), {
	// Configuration details.
} )
.then( editor => {
	const wordCountPlugin = editor.plugins.get( 'WordCount' );
	const wordCountWrapper = document.getElementById( 'word-count' );

	wordCountWrapper.appendChild( wordCountPlugin.wordCountContainer );
} )
```

2024-03-13 08:08 UTC, gorzelinski commented on packages/ckeditor5-word-count/docs/features/word-count.md
There are still `catch()` blocks in this guide.

2024-03-13 08:25 UTC, godai78 commented on packages/ckeditor5-ckfinder/docs/features/ckfinder.md
In commit.

2024-03-13 08:25 UTC, godai78 commented on packages/ckeditor5-word-count/docs/features/word-count.md
In commit.

2024-03-13 11:14 UTC, filipsobol commented on packages/ckeditor5-language/docs/features/language.md
> +			{ title: 'Spanish', languageCode: 'es' }
```suggestion
			{ title: 'Arabic', languageCode: 'ar' },
			{ title: 'French', languageCode: 'fr' },
			{ title: 'Hebrew', languageCode: 'he' },
			{ title: 'Spanish', languageCode: 'es' }
```

2024-03-13 11:15 UTC, filipsobol commented on packages/ckeditor5-list/docs/features/lists-editing.md
> +	],
```suggestion
	plugins: [ List, AdjacentListsSupport, /* ... */ ],
```

2024-03-13 11:16 UTC, filipsobol commented on packages/ckeditor5-minimap/docs/features/minimap.md
> +.catch( /* ... */ );
```suggestion
} );
```

2024-03-13 11:51 UTC, merged