Add menu bar button for media embed.
ckeditor/ckeditor5 pull request #16337
Opened 2024-05-10 10:39 UTC by mremiszewski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

WIP: Message. Closes #000.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2024-05-16 07:35 UTC, DawidKossowski requested changes
There are still several things to fix/improve:

1. You should add the `Dialog` plugin to `requires` in `mediaembedui.ts`.
2. IMO, the dialog is too small. We could discuss it at the daily meeting.
3. The dialog content does not clear after closing, resulting in the bug where the input label hovers over the starting input value (after reopening the modal):

https://github.com/ckeditor/ckeditor5/assets/20561161/0327fea4-e5c5-4ac2-a20a-0ea8db34e033

4. Unit tests are still missing.

2024-05-16 07:35 UTC, DawidKossowski commented on packages/ckeditor5-media-embed/src/mediaembedui.ts
> +			} );
```suggestion
			button.tooltip = true;
```

When we set only one value we rather use the shorthand form.

2024-05-16 07:35 UTC, DawidKossowski commented on packages/ckeditor5-media-embed/src/mediaembedui.ts
> +		// if ( !this.formView ) {
Why did you comment it out? I believe we do not want to create a new view each time.

2024-05-17 14:58 UTC, mremiszewski commented
Ad 3. is still not fixed, I'm waiting for a decision about the way it will be handled.

2024-05-22 12:46 UTC, scofalik requested changes
In general LGTM. I tested it manually a bit and it looks good. Mostly minor changes except that it should be a centered modal.

2024-05-22 12:46 UTC, scofalik commented on packages/ckeditor5-media-embed/tests/mediaembedui.js
> +		// button.element.remove();
Remove this line if it is not needed.

2024-05-22 12:46 UTC, scofalik commented on packages/ckeditor5-media-embed/tests/mediaembedui.js
> +			// menuBarButton.element.remove();
Same here, remove if not needed.

2024-05-24 12:31 UTC, scofalik requested changes
One minor thing. I'd change it myself but there may be a related unit test. If there's not maybe we should check how the modal is opened (with what params?)

2024-05-24 12:57 UTC, mremiszewski commented on packages/ckeditor5-media-embed/src/mediaembedui.ts
> +			position: DialogViewPosition.EDITOR_CENTER,
Done

2024-05-29 14:15 UTC, merged