Docs: updating legacy infoboxes.
ckeditor/ckeditor5 pull request #16545
Opened 2024-06-11 12:19 UTC by godai78

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Docs: updating legacy infoboxes. Part of: #16539

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2024-06-12 12:06 UTC, gorzelinski requested changes
I found small issues.

2024-06-12 12:06 UTC, gorzelinski commented on docs/getting-started/advanced/integrating-from-source-vite.md
I also wondered about this version of the info box. Some of them sound similar.

> ⚠️  This is a legacy guide kept for users' convenience. If you want to learn more about these changes, please refer to the Migrating to new installation methods guide.

But what changes? It may not be clear. I would suggest something like below.

> We changed installation methods, and this is a legacy guide kept for users' convenience. If you want to learn more about these changes, please refer to the Migrating to New Installation Methods guide.

Or

> This is a legacy guide kept for users' convenience. If you want to learn more about current installation methods, please refer to the Migrating to New Installation Methods guide.

2024-06-12 12:24 UTC, godai78 commented on docs/getting-started/advanced/integrating-from-source-vite.md
> We changed installation methods, and this legacy guide is kept for users' convenience.

2024-06-12 12:50 UTC, gorzelinski approved these changes
Now, LGTM

2024-06-14 10:44 UTC, Witoso approved these changes
I smoke test it with random docs clicks, and haven't found anything wrong.

2024-06-14 10:49 UTC, merged