Add menu bar to remaining editor types.
ckeditor/ckeditor5 pull request #16591
Opened 2024-06-18 12:19 UTC by mremiszewski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Type: Message. Closes #000.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2024-06-24 06:17 UTC, DawidKossowski requested changes
@mremiszewski, In the case of the balloon editor, we cannot include the menu bar inside the balloon as it breaks the UX. Instead, we should handle it similarly to the multi-root editor. You should provide an independent element that integrators can render in any place. After making this change, moving the entire logic to `EditorUI` should be possible.

2024-06-26 06:03 UTC, Mati365 commented on packages/ckeditor5-ui/src/editorui/editorui.ts
> +		} );
This handler has to be extended after merging this PR: https://github.com/ckeditor/ckeditor5/pull/16573, we added focus bordering flag assign on alt+f9.

2024-06-26 13:08 UTC, DawidKossowski reviewed
Just one comment. Besides that LGTM.

2024-07-03 00:49 UTC, Mati365 commented on packages/ckeditor5-ui/src/editorui/editorui.ts
> +		} );
I see that you migrate it, thanks!

2024-07-05 13:44 UTC, DawidKossowski requested changes
I just found that there are missing tests for `editor-balloon` in the context of the menu bar.

We also moved some logic from `ui/utils` to `ui/editorui`. Shouldn't we also move some unit tests (like focus handling tests)?

2024-07-08 07:23 UTC, DawidKossowski approved these changes

2024-07-08 14:55 UTC, merged