Changelog for v43.0.0
ckeditor/ckeditor5 pull request #16862
Opened 2024-08-05 12:41 UTC by psmyrek

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Internal: Changelog for v43.0.0.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2024-08-05 14:54 UTC, scofalik requested changes

2024-08-05 14:54 UTC, scofalik commented on CHANGELOG.md
> +
```suggestion
The new [merge fields feature](https://ckeditor.com/docs/ckeditor5/latest/features/merge-fields.html) is a game-changer for creating document templates and other kinds of personalized or dynamic content. Thanks to this feature, you can insert placeholders into your content, indicating where actual values should go. These places are marked in the final content in a distinctive way, making it easy to later process the template and fill it with the actual values. The feature supports a preview mode too -- you can define preview data sets, and see how the content will look like when real values are used directly in the editor. The plugin is highly customizable to fit various applications and scenarios. Finally, merge fields are fully integrated with our Export to Word, Export to PDF, and Import from Word features, both when they are used from the editor and via REST API.

We are extremely happy to share with you this highly demanded feature, and we cannot wait to listen to your feedback!

Make sure to visit our [builder](https://ckeditor.com/ckeditor-5/builder/) or [documentation](https://ckeditor.com/docs/ckeditor5/latest/features/merge-fields.html) to learn more about the feature.
```

2024-08-05 14:54 UTC, scofalik commented on CHANGELOG.md
> +We have introduced multiple enhancements to make the sidebar more accessible. You can now use `Shift+Ctrl+E` to move focus from the editor to the active annotation. Navigation has been improved with
```suggestion
We have introduced multiple enhancements to make the sidebar more accessible. Among other improvements, you can now use `Shift+Ctrl+E` to move focus from the editor marker to the active annotation. When your comment reply is ready, you can quickly submit it using a new `Ctrl+Enter` shortcut. Also, navigation from one annotation to another is now possible by using arrow keys.

The full lists of keyboard supported actions can be reviewed in our [Accessibility support guide](https://ckeditor.com/docs/ckeditor5/latest/features/accessibility.html#Keystrokes-for-interacting-with-annotation-threads-e-g-comments-track-changes-suggestions).
```

2024-08-05 14:54 UTC, scofalik commented on CHANGELOG.md
> +We have introduced multiple enhancements to make the sidebar more accessible. You can now use `Shift+Ctrl+E` to move focus from the editor to the active annotation. Navigation has been improved with
I am not sure if the link is correct I can verify it later or we can simplify it.

2024-08-06 13:26 UTC, scofalik commented
I will have a few more items for the changelog, please wait a bit.

2024-08-06 13:48 UTC, scofalik approved these changes

2024-08-07 06:08 UTC, godai78 approved these changes

2024-08-07 06:08 UTC, merged