Bookmark update label
ckeditor/ckeditor5 pull request #17175
Opened 2024-09-27 12:48 UTC by illia-stv

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Internal: Update the label name in form view

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2024-09-27 13:39 UTC, mmotyczynska requested changes
It was about changing `Add bookmark name` into `Bookmark name`, not `Add bookmark`.

2024-09-28 18:48 UTC, pszczesniak requested changes

2024-09-28 18:48 UTC, pszczesniak commented on packages/ckeditor5-bookmark/lang/contexts.json
> +	"Bookmark name": "The label of the input in the bookmark insert form.",
```suggestion
	"Bookmark name": "The label of the input in the bookmark insert and update form.",
```

2024-09-30 07:50 UTC, mmotyczynska approved these changes

2024-09-30 10:13 UTC, pszczesniak approved these changes

2024-09-30 10:23 UTC, merged