Add possibility to break the current block by `InsertImageCommand`
ckeditor/ckeditor5 pull request #17177
Opened 2024-09-27 13:46 UTC by Dumluregn

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Feature (image): Add possibility to break the current block by `InsertImageCommand` with `breakBlock` flag.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2024-09-30 14:06 UTC, scofalik submitted a review, later dismissed

2024-10-11 19:33 UTC, Dumluregn commented
Besides the previous `insertImage` command extension, now this PR also contains a few improvements related to tooltip manager (see the main PR comment).

2024-10-16 11:57 UTC, scofalik submitted a review, later dismissed
Approve, but as mentioned in merge fields PR, I'd consider having the "instant" tooltip also close "instantly".

2024-10-16 13:59 UTC, niegowski commented on packages/ckeditor5-ui/src/tooltipmanager.ts
>  			this._pinTooltip( elementWithTooltipAttribute, getTooltipData( elementWithTooltipAttribute ) );
```suggestion
		if ( 
			evt.name === 'focus' && !elementWithTooltipAttribute.matches( ':hover' ) ||
			elementWithTooltipAttribute.matches( '.ck-with-instant-tooltip' )
		) {
			this._pinTooltip( elementWithTooltipAttribute, getTooltipData( elementWithTooltipAttribute ) );
```

2024-10-28 11:49 UTC, scofalik commented on packages/ckeditor5-ui/src/tooltipmanager.ts
>  				this._unpinTooltipDebounced();
I didn't analyze it, but shouldn't this be in `} else {`?

2025-01-10 14:08 UTC, scofalik requested changes
Almost there.

2025-01-10 14:08 UTC, scofalik commented on packages/ckeditor5-image/src/image/imageblockediting.ts
> +				}
It seems like nothing changed here (or I am blind). It could be that you changed the notation to debug something and then did not revert it.

2025-01-10 14:14 UTC, Dumluregn commented on packages/ckeditor5-clipboard/src/clipboardpipeline.ts
> +			const content = editor.data.toView( data.content, { usingClipboardPipeline: true } );
Switched to `isClipboardPipeline`.

2025-01-10 15:29 UTC, scofalik approved these changes

2025-01-10 16:07 UTC, merged