Bookmark id validation
ckeditor/ckeditor5 pull request #17186
Opened 2024-09-30 13:31 UTC by illia-stv

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Internal: Bookmark id validation in command.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2024-09-30 14:39 UTC, mmotyczynska commented
I'm not sure if it's a good idea to log a warning **only** when the `name` contains spaces. I think we should either log a warning for **all invalid cases** (such as a missing/empty `name` or non-string `name`), or not warn at all and simply return early from command execution, as it was implemented before.

I'd prefer option 1 to maintain consistency and to inform the user when something is wrong with the `name`. WDYT @pszczesniak ?

Reference code:
```
		if ( !bookmarkId || typeof bookmarkId !== 'string' ) {
			return;
		}


		if ( !isBookmarkIdValid( bookmarkId ) ) {
			/**
			 * Insert bookmark command can be executed only with a valid id.
			 *
			 * Spaces are not allowed in the bookmark id.
			 *
			 * @error insert-bookmark-command-executed-with-invalid-id
			 */
			logWarning( 'insert-bookmark-command-executed-with-invalid-id' );


			return;
		}
```

2024-10-01 05:33 UTC, pszczesniak reviewed
Yes @mmotyczynska , i agree, cause throwing an error on one case and not on other may confuse a user, when result will always be be the same - bookmark wont be added.

2nd thing to be remembered: gathering error codes to create `error-codes` page in docs. 

Every error will be reflected there, and when you add same error more than once, it will be there same amount of times. Example https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-annotationsuis-missing-ui

2024-10-01 12:48 UTC, mmotyczynska requested changes

2024-10-01 16:00 UTC, mmotyczynska requested changes

2024-10-02 11:22 UTC, mmotyczynska approved these changes

2024-10-02 11:43 UTC, merged