The link `rel` attribute should be handled as a token list to allow mixing manual link decorators for the same attribute
ckeditor/ckeditor5 pull request #17461
Opened 2024-11-14 09:38 UTC by niegowski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (engine): The link `rel` attribute will now allow mixing manual link decorators for the same attribute, as it will be now handled as a token list. Closes #13985, closes #6436.

Fix (mention): Mention should not be wrapped with an additional `<span>` when GHS is enabled. Closes #15329.

Internal (html-support): Attribute matching updated to the new output of `Matcher#matchAll()`.

MINOR BREAKING CHANGE (engine): The `ViewConsumable.consumablesFromElement()` is removed and replaced with `view.Element#_getConsumables()` internal method. You should use `ViewConsumable.createFrom()` To create consumables if needed.

MINOR BREAKING CHANGE (engine): The `ViewElementConsumables` now accepts and outputs only normalized data. The `ViewConsumable` still accepts normalized or non-normalized input.

MINOR BREAKING CHANGE (engine): The `Matcher#match()` and `Matcher#matchAll()` output is now normalized. The `MatchResult#match` now contains normalized data compatible with changes in the `ViewConsumable`.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2024-12-17 16:02 UTC, Witoso commented
@niegowski added `closes` [`#6436`](https://github.com/ckeditor/ckeditor5/issues/6436) as I think we mentioned it fixes this one as well.

2024-12-17 16:04 UTC, Witoso commented
Before merging, let's discuss the release strategy, if it's coupled or not with linking experience.

2025-01-09 11:45 UTC, scofalik requested changes
It's hard for me to approach this PR from top-level point of view and decide whether it is the best way to do it, but **in overall, it makes sense and looks good**. I rather focused on particular bits of code and possible logical/algorithmical/typo errors.

My two questions marks are:

1. I am not sure if it was a good decision to move some of the code to view elements. I mean generating consumables and merging elements. I don't know what was the reason to move it (e.g. if multiple parts of the code wanted to perform the same logic and view element was the best to keep it). If you decide that this is a must have, I'd recommend taking care to see if all related elements are moved. In one place I commented that it is weird that view element imports a type from conversion. I had such feeling a few times. Right now I am not convinced that moving code to view elements was a necessary change, but I don't have the holistic view on this PR/improvement, you spent more time on it.
2. Performance. Could you confirm that the performance does not drop, especially for samples where there is a lot of merging and unwrapping of view attribute elements (`formattingLongPs`, `inlineStyles`, `wiki`, `ghs` from the recently introduced performance tests).

2025-01-09 11:46 UTC, scofalik commented on packages/ckeditor5-engine/src/view/element.ts
> +						new StylesMap( this.document.stylesProcessor ).setTo( String( value ) )
Same below.

2025-01-23 14:20 UTC, niegowski commented on packages/ckeditor5-engine/src/conversion/viewconsumable.ts
> +		else if ( from.is( 'element' ) || from.is( 'documentFragment' ) ) {
As `from` is an instance of `Node | DocumentFragment`, it could be any class extending a `Node`, so we need that check just for type narrowing.

2025-01-23 14:43 UTC, niegowski commented on packages/ckeditor5-engine/src/conversion/viewconsumable.ts
> +				if ( !attributeTokens || typeof attributeTokens == 'boolean' ) {
No. No real-life scenario. Just for completeness of the API. It would not assume the input is generated only by our tools.

2025-01-23 15:02 UTC, niegowski commented on packages/ckeditor5-engine/src/view/element.ts
> +				this._attrs.set( key, currentValue );
No, the new StylesMap/TokenList is empty at this point and value is set later in a common code for already existing attribute.

2025-01-23 15:06 UTC, niegowski commented on packages/ckeditor5-engine/src/view/stylesmap.ts
> +	public isSimilar( other: StylesMap ): boolean {
This is a subroutine for `Element#isSimilar()` and it is a bit loosely checked as for example class list could have a different order but still would be similar.

2025-01-23 15:09 UTC, niegowski commented on packages/ckeditor5-engine/src/view/tokenlist.ts
> +	public _getTokensMatch(
It's only for performance reasons so we do not have to iterate it again.

2025-01-23 15:13 UTC, niegowski commented on packages/ckeditor5-engine/src/view/matcher.ts
> +		if ( attributesMatch.length ) {
Added a comment. This is for performance reasons.

2025-01-23 16:04 UTC, niegowski commented on packages/ckeditor5-engine/src/view/attributeelement.ts
> +	protected override _canMergeAttributesFrom( otherElement: AttributeElement ): boolean {
explained F2F.

2025-01-23 16:20 UTC, niegowski commented on packages/ckeditor5-engine/src/view/element.ts
> +			.sort().join( ' ' );
We do not sort in the TokenList, so I couldn't use it here because I wanted to keep it backward compatible.

2025-01-23 16:25 UTC, niegowski commented on packages/ckeditor5-engine/src/view/tokenlist.ts
> +	public setTo( value: string ): this {
Because we want to keep the same interface with StylesMap.

2025-01-23 16:36 UTC, niegowski commented on packages/ckeditor5-engine/src/view/tokenlist.ts
> +		return name ? [ name ] : this.keys();
This is for interface consistency with StylesMap.

2025-01-23 16:47 UTC, niegowski commented on packages/ckeditor5-engine/src/view/stylesmap.ts
> +			result.push( name );
This was moved from the previous implementation.

2025-01-23 16:47 UTC, niegowski commented on packages/ckeditor5-engine/src/view/stylesmap.ts
> +		return true;
It's not exactly the same.

2025-01-23 17:22 UTC, niegowski commented on packages/ckeditor5-engine/src/view/tokenlist.ts
> +	public _getTokensMatch(
Fixed.

2025-01-23 17:43 UTC, niegowski commented on packages/ckeditor5-engine/src/view/element.ts
> +		if ( !this._canMergeAttributesFrom( otherElement ) ) {
Fixed.

2025-01-23 17:43 UTC, niegowski commented on packages/ckeditor5-engine/src/view/downcastwriter.ts
> +			if ( isAttribute && ( child as AttributeElement )._mergeAttributesFrom( wrapElement ) ) {
Fixed.

2025-01-30 16:04 UTC, scofalik approved these changes

2025-01-30 16:04 UTC, scofalik commented
Please use squash and merge :smile:.

2025-01-31 12:21 UTC, merged