Other: Update the logic of the check.
ckeditor/ckeditor5 pull request #17651
Opened 2024-12-16 13:28 UTC by gorzelinski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Other: Update the logic of the check.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2024-12-16 13:38 UTC, gorzelinski commented on packages/ckeditor5-core/src/editor/editor.ts
> +			}
I thought about extracting logging into a separate if block for all types. But, after the change those type differ, so it's probably better this way.

2024-12-17 11:34 UTC, arkflpc requested changes

2024-12-17 11:34 UTC, arkflpc commented on packages/ckeditor5-core/tests/editor/licensecheck.js
> +			it( 'also should not block editor after 10 minutes (development license)', () => {
```suggestion
			it( 'should not block editor after 10 minutes (development license)', () => {
```

2024-12-17 12:42 UTC, arkflpc approved these changes

2024-12-17 13:00 UTC, merged