Prevent bookmark popup flickering when clicking paragraphs with trailing bookmarks.
ckeditor/ckeditor5 pull request #17690
Opened 2024-12-23 15:42 UTC by Mati365

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/contributing/git-commit-message-convention.html))

Fix (bookmark): Prevent bookmark popup flickering when clicking paragraphs with trailing bookmarks.

---

### Additional information

When a widget (e.g., a bookmark anchor) is clicked, two consecutive `update` events may fire:

1. First, when the widget gets focused (this is fine)
3. Second, when the selection changes shortly after (beware, dragons live here)

While the widget usually stays selected, sometimes the selection may move to a different element (e.g., to the start of the parent paragraph). This can cause the toolbar to flicker as it's quickly shown and hidden.

This issue particularly affects widgets like anchors that contain a single SVG element. 

Making the element `inline-block` seems to reduce flickering. 

#### Before

https://github.com/user-attachments/assets/c931542c-fe3a-439a-9cf8-2070355d72a9

#### After

https://github.com/user-attachments/assets/7200e9b3-e3c6-4222-be14-fed75f83254e

2025-01-07 18:01 UTC, niegowski requested changes
I suggest fixing the bookmark stylesheet instead. Adding `display: inline-block;` to the `.ck-bookmark.ck-widget` selector should fix the problem.

2025-01-08 08:36 UTC, pszczesniak commented
Fix that @niegowski suggested doesn't eliminate it completely, but it limits it more.

It also fixes issue shown on the video (clicking at the end of paragraphs):

https://github.com/user-attachments/assets/5155b4da-fb0f-496f-926c-8fffc79ff414

2025-01-08 15:59 UTC, niegowski approved these changes

2025-01-08 15:59 UTC, niegowski commented
Please update the PR title.

2025-01-09 06:24 UTC, merged