Migrate
ckeditor/ckeditor5 pull request #8046
Opened 2020-09-09 08:18 UTC by godai78

### Migrate update.

Closes cksource/content-documentation-proofread#314

Closes cksource/content-documentation-proofread#289

New feature added, deprecated configuration options removed (not used anywhere outside the migration document).

2020-09-10 06:28 UTC, AnnaTomanek commented
This should be targeted at `stable` as it concerns an already released version.

2020-09-10 06:33 UTC, AnnaTomanek commented
2\. It looks like you missed quite a few new configuration options. Can you go to https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html, search "4.15" on this page and add all found items?

2020-09-10 06:34 UTC, AnnaTomanek requested changes
There are still plenty of new options that were not covered.

2020-09-10 10:43 UTC, AnnaTomanek commented on docs/builds/guides/migrate.md
> +			<a href="../../../../ckeditor4/latest/api/CKEDITOR_config.html#cfg-exportPdf_fileName">exportPdf_fileName</a> <br><a href="../../../../ckeditor4/latest/api/CKEDITOR_config.html#cfg-exportPdf_optio
```suggestion
			<a href="../../../../ckeditor4/latest/api/CKEDITOR_config.html#cfg-exportPdf_fileName">exportPdf_fileName</a> <br><a href="../../../../ckeditor4/latest/api/CKEDITOR_config.html#cfg-exportPdf_options">exportPdf_options</a> <br> <a href="../../../../ckeditor4/latest/api/CKEDITOR_config.html#cfg-exportPdf_service">exportPdf_service</a> <br> <a href="../../../../ckeditor4/latest/api/CKEDITOR_config.html#cfg-exportPdf_stylesheets">exportPdf_stylesheets</a> <br> <a href="../../../../ckeditor4/latest/api/CKEDITOR_config.html#cfg-exportPdf_tokenUrl">exportPdf_tokenUrl</a> <br>
```

2020-09-10 10:47 UTC, AnnaTomanek commented on docs/builds/guides/migrate.md
> +				Refer to the {@link features/export-pdf Export to PDF feature} guide to learn more about about configuring PDF converter in CKEditor 5.
```suggestion
				Refer to the {@link features/export-pdf Export to PDF feature} guide to learn more about about configuring the HTML to PDF converter in CKEditor 5.
```

2020-09-10 10:56 UTC, AnnaTomanek approved these changes
Looks good now!

2020-09-10 10:57 UTC, merged

2021-06-01 08:05 UTC, harleenarora commented
How to migration CKEditor 4 data in CKE4.15?