Reflecting commands state by save button.
ckeditor/ckeditor5 pull request #8421
Opened 2020-11-05 21:30 UTC by pkwasnik

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (html-embed): Reflecting commands state by save button. Closes #8357.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2020-11-09 06:57 UTC, jodator requested changes
I think that we didn't check this case when implementing HTML embed so a new solution or a fix must be provided for the buttons used there.

At this moment I wonder if:
- We need to destroy the button at all - thus we would have the `ButtonView` binding working - OTOH I'm not sure if that binding it to a command will not leak memory.
- Simple listener to change button state might be enough (using VanillaJS framework ;) )
- Again, we must ensure that this will not leak the momory.

2020-11-09 06:57 UTC, jodator commented on packages/ckeditor5-html-embed/src/htmlembedediting.js
> +		buttonView.bind( 'isEnabled' ).to( command, 'isEnabled' );
Unfortunately, the button is destroyed (see below) here and w only use `ButtonView` to render the DOM element (by using `cloneNode()` below.

The problem with this that you can still click and execute the button. The disabled state is taken into consideration only when the button is created.

The best way to test it in the manual test is to change the editor state to ["read-only"](https://ckeditor.com/docs/ckeditor5/latest/features/read-only.html) by executing in the console:

```
editor.isReadOnly = true;
```

![](https://user-images.githubusercontent.com/247363/98508455-ca86c700-225f-11eb-99ee-2395f957691f.gif)

2020-11-09 13:12 UTC, jodator commented
After quick talk during sync - we didn't use `ButtonView` instances there because of memory leaks. There's a work-around to use a view [post-fixer](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_view_document-Document.html#function-registerPostFixer). You should be able to check which views are not in the view root anymore and run `buttonView.destroy()` to detach listeners (created by `view.bindTo()` call.

The "edit" button must be disabled as well when the command is disabled (note that there are 2 commands - one for inserting and one for editing which I wasn't aware before).

2020-11-12 15:12 UTC, pkwasnik commented
Clicking "save" will return to preview only when there are no changes (this a "feature" made on purpose). Otherwise button will not work:

![](https://user-images.githubusercontent.com/16957311/98957433-7bf85780-2501-11eb-8a98-8dfe81610f48.gif)

About `edit` button there is a bug that is blocks it. Currently, edit command is disabled when the focus is outside of the editor. If we will link the `edit` state to that command than button will be disabled until the widget will be clicked. There is a bug open for serveral similar cases, including this one: #8328

2020-11-20 13:23 UTC, jodator approved these changes
After reading this over and over I agree that in the current state the least we can do is to disable the save button. I don't like this feature UX but let live with it for a while.

Sorry for longer review @pkwasnik, everything is OK now. According to the ticket description and later talks :+1:

2020-11-20 13:24 UTC, merged