Introducing DataProcessor#registerRawContentElementMatcher()
ckeditor/ckeditor5 pull request #8529
Opened 2020-11-25 17:45 UTC by niegowski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Feature (engine): Introducing `DataProcessor#registerRawContentElementMatcher()`. 

Fix (html-embed): Editor should not crash after inserting a broken HTML. Closes #8323.

Fix (engine): `DomConverter` should not trim whitespaces in nodes that are siblings to inline raw content elements (e.g. MathML). Closes #5870.

---

### Additional information

2020-11-26 11:52 UTC, jodator requested changes
I would add more tests for the new method. We should add more test cases to define what happens in a scenario, where two or more features registers raw content.

The method name is a bit long, so I've proposed a shorter one as I think that `Element` part is redundant. But that's up to you to decide whether you think that's a valid comment.

2020-11-26 11:52 UTC, jodator commented on packages/ckeditor5-engine/src/view/domconverter.js
> +		this._rawContentElementMatcher.add( pattern );
WDYT about changing the name to a bit shorter: `registerRawContentMatcher()` ?

2020-11-26 11:52 UTC, jodator commented on packages/ckeditor5-engine/src/view/domconverter.js
> +	 * @param {module:engine/view/matcher~MatcherPattern} pattern Pattern matching all view elements whose content should
```suggestion
	 * @param {module:engine/view/matcher~MatcherPattern} pattern Pattern matching view element which content should
```

2020-11-26 11:52 UTC, jodator commented on packages/ckeditor5-engine/tests/view/domconverter/dom-to-view.js
> +		it( 'should assign $rawContent custom property for view elements registered as raw content elements', () => {
Too few tests IMO. Right now it tests only one pattern. I think that we could check a bit more:

*   multiple patterns registered
*   what if `div.raw-content-container` has other attributes, classed or styles, ie `div[ data-foo="bar"].raw-content-container`

2020-11-26 14:02 UTC, Reinmar commented on packages/ckeditor5-engine/src/view/domconverter.js
> +		 * @type {WeakSet<Node>}
```suggestion
		 * @type {WeakSet.<Node>}
```

2020-11-28 10:15 UTC, jodator approved these changes
Thanks! :+1:

2020-11-28 10:27 UTC, merged