I/6267
ckeditor/ckeditor5 pull request #8536
Opened 2020-11-26 17:55 UTC by pkwasnik

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Feature (docs): Mark UI buttons in the guides. Closes #6267.

---

### Additional information

I've left a usage example in html-embed feature docs. To be deleted before merging.

To use it in any snippet, first import function: 

```
import { pinTourBalloon } from '@ckeditor/../../docs/assets/button-indicator.js';
```

Then execute it with desired parameters inside `.then( editor => { } )` block:

```
Editor.create( document.querySelector(  ) )
	.then( editor => {
		pinTourBalloon(
			editor,
			window.selectToolbarButton( 9 ),
			'Click this button to create a raw html widget.'
		);
	}
```

Required parameters:

1.  editor object
2.  button selector
    1.  there is `window.selectToolbarButton( buttonPosition )` helper function, which needs only the button position parameter
3.  message

![](https://user-images.githubusercontent.com/16957311/100380651-86dddc80-3017-11eb-848d-0bb7505ef055.png)

2020-12-02 08:58 UTC, pkwasnik commented
I'd prefer a lighter border to distinguish it more from the UI border, e.g.: #D9D9D9 / hsl(0, 0%, 87%), but I am not sure if I should use only existing color vars or create a new one (and where to put it).

![](https://user-images.githubusercontent.com/16957311/100850174-c24b3180-3483-11eb-9c72-2edc51e8ec9c.png)

2020-12-07 16:27 UTC, oleq requested changes
While I'm totally digging the look and feel of the balloon 💕, I also have certain concerns regarding the implementation.

I'm not sure why you went with the implementation that relies on ckeditor5-ui. Browsing the discussion under the issue I got the impression that [we dumped this tempting concept of using the `BalloonPanelView`](https://app.zenhub.com/workspaces/ckeditor-5-5d9c8a4eac250d0001664feb/issues/ckeditor/ckeditor5/6267#issuecomment-594413950) because it:
1. requires importing `import { pinTourBalloon } from '@ckeditor/../../docs/assets/button-indicator.js';` in every snippet file (which is a PITA)
2. effectively makes `ckeditor5` a dev dependency of (almost) every `ckeditor5-*` package for the sole purpose of importing a single helper, which is just wrong.

Have I missed something? I thought we're going with an external library to spare ourselves the hassle. @Reinmar, did you have an impact on this decision?

Anyway, also I spotted some issue with an error being thrown when the button that should get the tour balloon gets immediately wrapped in the "kebab dropdown" due to the narrow geometry of the viewport when the editor loads. But before we move on to this, maybe let's sort out this implementation toolkit decision as it may affect this and similar issues.

2020-12-08 10:40 UTC, pkwasnik commented on docs/assets/snippet.js
> +window.selectToolbarButton = function( buttonPosition ) {
My mistake, I misunderstood that. But switching now to an external library will not be a big deal as I already have it prepared in one of the previous PoC. Anyway, it will also require to be imported in every snippet, or there is another solution?

2020-12-08 11:15 UTC, oleq commented on docs/assets/snippet.js
> +window.selectToolbarButton = function( buttonPosition ) {
Can we import it once in `snippet.js` and store the reference somewhere in `window` or other namespace?

2020-12-16 14:40 UTC, merged