Docs feat landing
ckeditor/ckeditor5 pull request #8808
Opened 2021-01-12 07:22 UTC by godai78

Features landing page revamp as recommended in #5703 

This is a kick-off draft for possible further development.

2021-06-16 13:36 UTC, FilipTokarski commented
It looks really nice, can we add a section about Revision History?

2021-06-17 07:49 UTC, godai78 commented
Revision History added.

2021-06-17 11:24 UTC, FilipTokarski requested changes
Just some small typos. Other than that, it looks cool 👍

2021-06-17 11:24 UTC, FilipTokarski commented on docs/features/index.md
> +Track your progress and changes done in the content with the {@link features/revision-history revision history} feature. This modern and robust document versioning tools lets you create named version
Shouldn't it be `tool` instead of `tools`?

2021-06-17 11:24 UTC, FilipTokarski commented on docs/features/index.md
> +Additionally, CKEditor 5 offers the {@link features/restricted-editing restricted editing mode} where only selected part of the content may be edited by selected users, based on permissions system. A
lets the `uses` => lets the `users`

2021-06-17 11:24 UTC, FilipTokarski commented on docs/features/index.md
> +Work as you like it - choose user interface approach from {@link examples/index several preconfigured build}, add or remove features easily to your build with the [online builder](https://ckeditor.co
several preconfigured `build` => several preconfigured `builds`

2021-06-17 11:24 UTC, FilipTokarski commented on docs/features/index.md
> +If you need to share the document, use [export to PDF feature](https://ckeditor.com/docs/ckeditor5/latest/features/export-pdf.html) to produce industry standard, portable, cross-platform final files.
keep your `comment` and changes => keep your `comments` and changes ?

2021-06-17 12:25 UTC, FilipTokarski approved these changes
LGTM.

2021-06-17 15:12 UTC, merged