Integrated inline images with responsive images (srcset, sizes)
ckeditor/ckeditor5 pull request #9043
Opened 2021-02-17 13:21 UTC by pkwasnik

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Internal (image): Integrated inline images with responsive images. Closes #8777.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2021-02-23 17:10 UTC, oleq requested changes
The feature is incomplete. There's no support for resizing handles 
![image](https://user-images.githubusercontent.com/1099479/108880005-1fc5c900-7602-11eb-8bc7-e0a25318b741.png).

Also, the upcast conversion pipeline configuration is incorrect. You can check it by setting a size for an inline image in a manual test and doing `editor.setData( editor.getData() );`

2021-02-23 17:10 UTC, oleq commented on packages/ckeditor5-image/tests/imageresize/imageresizeediting.js
> +		} );
What about upcasting just `<img style="width: ...">`? Inline images don't exist in the editor data pipeline as `<span><img /></span>` – this is an editing pipeline representation.

2021-02-23 17:10 UTC, oleq commented on packages/ckeditor5-image/tests/imageresize/imageresizeediting.js
> +		} );
Even the next text confirms this :point\_down:

2021-02-23 17:10 UTC, oleq commented on packages/ckeditor5-image/src/imageresize/imageresizeediting.js
> +					name: imageType === 'image' ? 'figure' : 'span',
This conversion is incorrect. In the case of inline images, the upcasted data will be `<img />` but not `<span><img /></span>` (see my comment in tests).

2021-03-15 14:03 UTC, magda-chrzescian commented
@oleq Resizing the images with the `srcset` causes content jumping in chrome (for both block and inline images):

![resizing](https://user-images.githubusercontent.com/14334820/111165438-4e9ae380-859f-11eb-9b2a-3419bde19d9b.gif)
---
The inline images are being resized only horizontally in Safari:
![Resizing](https://user-images.githubusercontent.com/14334820/111165565-7a1dce00-859f-11eb-8f4b-d233314d80df.gif)

2021-03-15 16:31 UTC, oleq commented
I addressed the Safari issue in [fcd1cfc](https://github.com/ckeditor/ckeditor5/pull/9043/commits/fcd1cfc3a58f39b283068049df4a98c44a26b511). I couldn't reproduce the latter, though. Any ideas?

2021-03-16 07:19 UTC, magda-chrzescian approved these changes
As in the comment: https://github.com/ckeditor/ckeditor5/pull/9043#issuecomment-799445766

2021-03-16 07:27 UTC, magda-chrzescian commented
> I addressed the Safari issue in [fcd1cfc](https://github.com/ckeditor/ckeditor5/pull/9043/commits/fcd1cfc3a58f39b283068049df4a98c44a26b511). I couldn't reproduce the latter, though. Any ideas?

I can't reproduce it either, but it wasn't a single case while I was testing. I guess we can merge anyway and keep an eye on it in the inline-images branch and while the QA testing.

2021-03-16 08:49 UTC, merged