Drag&drop of text and widgets
ckeditor/ckeditor5 pull request #9129
Opened 2021-03-01 10:35 UTC by niegowski

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

---

### Additional information

2021-03-09 13:12 UTC, FilipTokarski commented
## Steps to reproduce:
1. Create a list containing a few list items
2. Select it
3. Drag and drop somewhere else

## Expected:
Whole list gets moved, nothing remains.

## Actual:
Empty list remains at the original position.

https://user-images.githubusercontent.com/34380544/110474713-4b57b180-80e0-11eb-8fe8-669a0521306c.mp4

2021-03-09 13:15 UTC, FilipTokarski commented
## Steps to reproduce:
1. Create a list containing only one list item
2. Select it
3. Drag and drop somewhere else

## Expected:
List gets moved to new position

## Actual:
Empty list remains at the original position, dropped content is just text
  

https://user-images.githubusercontent.com/34380544/110475785-97572600-80e1-11eb-808c-7e211eaacad9.mp4

2021-03-09 13:27 UTC, LukaszGudel commented
## Steps to reproduce:
1. Open manual test in Safari.
2. Select some text.
3. Try to drag selected text.

## Expected:
Text can be draged and droped.

## Actual:
Selection is changing.


https://user-images.githubusercontent.com/58658048/110477264-3f212380-80e3-11eb-8791-17fe153005ed.mp4


## Notes:
- my Safari version 14.0.2
- my os: Big Sur 11.1

2021-03-09 13:54 UTC, FilipTokarski commented
## Steps to reproduce:
1. Add some text
2. Click `Align center`
3. Select it
4. Drag into empty paragraph

## Question:
If you select the text with a mouse, or by double-clicking, after DnD alignment will not be preserved. However if you select it by triple-click, the dropped content will be centered. Similar cases with selection exist when you [copy/paste content](https://github.com/ckeditor/ckeditor5/issues/8683#issuecomment-746106567) and here in DnD, it can sometimes create unexpected behaviors ( like lists issue above ). Now, is this selection thing some bug inside editor, or should we treat this as normal behavior?

2021-03-09 14:26 UTC, LukaszGudel commented
### Steps to reproduce:
1. Open manual test in Safari.
2. Add embedded media (youtube video).
3. Try to drag it.

### Result:
Unable to drag embedded media widget.

### Notes:
- my Safari version 14.0.2
- my os: Big Sur 11.1
- embedded medias are draggable in Chrome

2021-03-09 15:14 UTC, FilipTokarski commented
## Steps to reproduce:
1. Add image and code block
2. Try to drag image into the codeblock

## Expected:
Because images inside code blocs are not allowed, I'd expect nothing to happen ( the image shoud stay on its place )

## Actual:
The image disappears. 
 Apart from this, if the image has text alternative or captions, their text gets pasted into code block ( but I'm not 100% sure how this should behave TBH )

  

https://user-images.githubusercontent.com/34380544/110490555-bc9f6080-80f0-11eb-8e98-5edc30bf9fa8.mp4

2021-03-09 16:08 UTC, niegowski commented
## **Steps to reproduce:**

1.  Drag some image from local disc
2.  Drop it in the middle of some text

## **Expected:**

An image should split the paragraph exactly where it was dropped.

## **Actual:**

`findOptimalInsertionPosition()` corrects drop position to avoid splitting paragraphs.

![](https://user-images.githubusercontent.com/1232187/110501029-1193a480-80fa-11eb-8ee9-7ce1fdae7b45.gif)

2021-03-10 09:50 UTC, Reinmar commented
> 1.  Drag some image from local disc
> 2.  Drop it in the middle of some text

[https://github.com/ckeditor/ckeditor5/pull/9129#issuecomment-794098198](https://github.com/ckeditor/ckeditor5/pull/9129#issuecomment-794098198) -> it's currently being changed in the inline images task (cc @oleq – please consider this case too).

---

> 1.  Add image and code block
> 2.  Try to drag image into the codeblock

[https://github.com/ckeditor/ckeditor5/pull/9129#issuecomment-794029726](https://github.com/ckeditor/ckeditor5/pull/9129#issuecomment-794029726) -> edge case, followup, but low priority.

---

> 1.  Open manual test in Safari.
> 2.  Add embedded media (youtube video).
> 3.  Try to drag it.

[https://github.com/ckeditor/ckeditor5/pull/9129#issuecomment-793967533](https://github.com/ckeditor/ckeditor5/pull/9129#issuecomment-793967533) -> followup, medium priority; it'd be at least good to know why it fails.

---

> 1.  Add some text
> 2.  Click `Align center`
> 3.  Select it
> 4.  Drag into empty paragraph

Plus:

> 1.  Create a list containing only one list item
> 2.  Select it ( or double-click on list item )
> 3.  Drag and drop somewhere else

Plus:

> 1.  Create a list containing a few list items
> 2.  Select it
> 3.  Drag and drop somewhere else

[https://github.com/ckeditor/ckeditor5/pull/9129#issuecomment-793928495,](https://github.com/ckeditor/ckeditor5/pull/9129#issuecomment-793928495,) [https://github.com/ckeditor/ckeditor5/pull/9129#issuecomment-793883321,](https://github.com/ckeditor/ckeditor5/pull/9129#issuecomment-793883321,) https://github.com/ckeditor/ckeditor5/pull/9129#issuecomment-793880326 -> these issues deserve a general followup that would include copy-paste and drag and drop. Upper-medium priority, but it's also important to have a UX analysis of this. We shouldn't make a decision in a hurry.

---

To sum up, looking at the issues reported so far, there are no critical ones that would need to be solved in this PR.

2021-03-10 09:55 UTC, Reinmar commented on packages/ckeditor5-clipboard/src/clipboardpipeline.js
> +// Output pipeline events overview:
```suggestion
// Input pipeline events overview:
```

2021-03-10 09:55 UTC, Reinmar commented on packages/ckeditor5-clipboard/src/clipboardpipeline.js
> +// Input pipeline events overview:
```suggestion
// Output pipeline events overview:
```

2021-03-10 09:58 UTC, Reinmar commented on packages/ckeditor5-clipboard/src/dragdrop.js
> +//            │   │  clipboardInput  │   ( Default of clipboard pipeline ).
```suggestion
//            │   │  clipboardInput  │   ( Default handler of the clipboard pipeline ).
```

2021-03-10 12:11 UTC, Mgsy commented
(all browsers) Manual test issue

### Steps to reproduce

1.  Go to http://localhost:8125/ckeditor5-clipboard/tests/manual/dragdrop.html.
2.  Click somewhere outside of the editor to blur it.
3.  Ctrl + A.
4.  Start dragging from any contact item from the list and drag it to the right.

### Current result

The error occurs.

### Error

```
dragdrop.js:249 Uncaught TypeError: event.target.closest is not a function
    at HTMLUListElement.<anonymous> (dragdrop.js:249)
```

2021-03-10 12:14 UTC, niegowski commented on packages/ckeditor5-clipboard/src/dragdrop.js
> +//            │ │  inputTransformation  │   ( Default of clipboard pipeline ).
```suggestion
//            │ │  inputTransformation  │   ( Default handler of the clipboard pipeline ).
```

2021-03-10 12:14 UTC, niegowski commented on packages/ckeditor5-clipboard/src/dragdrop.js
> +//            │  │   contentInsertion  │   ( Default of clipboard pipeline ).
```suggestion
//            │  │   contentInsertion  │   ( Default handler of the clipboard pipeline ).
```

2021-03-10 12:18 UTC, Mgsy commented
(all browsers)

### Steps to reproduce

1.  Add a link to an inline widget.
2.  Drag and drop this widget.

### Current result

The editor crashes.

### Error

```
dragdrop.js:175 Uncaught TypeError: Cannot read property 'getChildren' of undefined
    at getAndConsumeText (dragdrop.js:175)
    at getAndConsumeHCardViewElement (dragdrop.js:168)
    at model (dragdrop.js:79)
    at getModelElement (upcasthelpers.js:792)
    at UpcastDispatcher.<anonymous> (upcasthelpers.js:768)
    at UpcastDispatcher.fire (emittermixin.js:194)
    at UpcastDispatcher._convertItem (upcastdispatcher.js:249)
    at UpcastDispatcher._convertChildren (upcastdispatcher.js:282)
    at UpcastDispatcher.<anonymous> (upcasthelpers.js:896)
    at UpcastDispatcher.fire (emittermixin.js:194)
```

2021-03-10 12:32 UTC, LukaszGudel commented
### Steps to reproduce:

1. Open manual test in Safari.
2. Add contact widget to the end of block element, as close as possible to the right side of editor.
3. Drag some text after the widget.

### Result:
Jumping widget :)

https://user-images.githubusercontent.com/58658048/110629115-1c0a7880-81a4-11eb-8cb1-f2be4e66c327.mp4

### Notes:
- low framerate on above video is not showing correct frequency of the jumping, it seems to jump much more frequent
- only in Safari
- only in Safari placing a caret after the widget in moving whole widget to the next line - in other browsers widget stays in the same line

2021-03-10 12:32 UTC, FilipTokarski commented
## Steps to reproduce:
1. Open three editors - one in Chrome, one in Firefox and one in Safari
2. Try dragging image from one browser into another and vice versa ( for simplicity, drag them into empty paragraphs )

## Expected:
You can drag the image in both ways in all browser combinations

## Actual:
1. Chrome => Firefox - image's text alternative and caption gets pasted as text
2. Chrome => Safari - nothing happens
3. Firefox => Chrome - works fine
4. Firefox => Safari - image disappears from FF but nothing happens inf Safari
5. Safari => Chrome - image gets pasted into Chrome, but remains in Safari
6. Safari => Firefox - image gets pasted into FF, but remains in Safari

2021-03-10 12:38 UTC, niegowski commented
> ### Steps to reproduce
> 
> 1.  Go to http://localhost:8125/ckeditor5-clipboard/tests/manual/dragdrop.html.
> 2.  Click somewhere outside of the editor to blur it.
> 3.  Ctrl + A.
> 4.  Start dragging from any contact item from the list and drag it to the right.
> 
> ### Current result
> 
> The error occurs.
> 
> ### Error
> 
> ```
> dragdrop.js:249 Uncaught TypeError: event.target.closest is not a function
>     at HTMLUListElement.<anonymous> (dragdrop.js:249)
> ```

Fixed in b7b19f6

2021-03-10 12:55 UTC, LukaszGudel commented
Seems similar to [#issuecomment-795349643](https://github.com/ckeditor/ckeditor5/pull/9129#issuecomment-795349643)

### Steps to reproduce:
1. Open 2 manual tests in 2 Safari windows
2. Drag any content from one editor to the other one.

### Result:
Content is correctly added to second editor but stays in the first one.

2021-03-10 13:03 UTC, FilipTokarski commented
## Steps to reproduce:
1. Create MS Word document with a list
2. Select the list and drag it into the editor

## Expected:
List is preserved

## Actual:
List items are converted into `<p>` tags

## Other info:
In the same test, pasting a list from Word works fine

## Screencast
![0_dnd1](https://user-images.githubusercontent.com/34380544/110633616-43177900-81a9-11eb-806c-205671ddfaf7.gif)

2021-03-10 13:48 UTC, FilipTokarski commented
## Steps to reproduce:
1. Create MS Word document with some image
2. Click on the image to select it
3. Copy and paste into the editor

## Result:
```js
imageuploadediting.js:114 Uncaught TypeError: Cannot read property 'map' of null
    at Object.<anonymous> (imageuploadediting.js:114)
    at Object.fire (emittermixin.js:194)
    at fireListenerFor (bubblingemittermixin.js:162)
    at Document.fire (bubblingemittermixin.js:92)
    at Object.<anonymous> (clipboardobserver.js:57)
    at Object.fire (emittermixin.js:194)
    at fireListenerFor (bubblingemittermixin.js:162)
    at Document.fire (bubblingemittermixin.js:92)
    at ClipboardObserver.fire (domeventobserver.js:96)
    at ClipboardObserver.onDomEvent (clipboardobserver.js:83)
```

## Other info:
- on `master` and live docs/demo image gets pasted without any errors

2021-03-10 14:32 UTC, niegowski commented
> ### Steps to reproduce
> 
> 1.  Go to http://localhost:8125/ckeditor5-clipboard/tests/manual/dragdrop.html.
> 2.  Add a link to an inline widget.
> 3.  Drag and drop this widget.
> 
> ### Current result
> 
> The editor crashes.
> 
> ### Error
> 
> ```
> dragdrop.js:175 Uncaught TypeError: Cannot read property 'getChildren' of undefined
>     at getAndConsumeText (dragdrop.js:175)
>     at getAndConsumeHCardViewElement (dragdrop.js:168)
>     at model (dragdrop.js:79)
>     at getModelElement (upcasthelpers.js:792)
>     at UpcastDispatcher.<anonymous> (upcasthelpers.js:768)
>     at UpcastDispatcher.fire (emittermixin.js:194)
>     at UpcastDispatcher._convertItem (upcastdispatcher.js:249)
>     at UpcastDispatcher._convertChildren (upcastdispatcher.js:282)
>     at UpcastDispatcher.<anonymous> (upcasthelpers.js:896)
>     at UpcastDispatcher.fire (emittermixin.js:194)
> ```

This should be resolved in 94896a9

2021-03-10 15:38 UTC, niegowski commented
> ## Steps to reproduce:
> 
> 1.  Create MS Word document with a list
> 2.  Select the list and drag it into the editor
> 
> ## Expected:
> 
> List is preserved
> 
> ## Actual:
> 
> List items are converted into `<p>` tags
> 
> ## Other info:
> 
> In the same test, pasting a list from Word works fine

I can not reproduce this issue, checked in Chrome, dragdrop manual test, dragging from the paste from Word sample document

2021-03-11 07:41 UTC, LukaszGudel commented
### Steps to reproduce:
1. Drag any content from Chrome or Word to Safari.

### Result:
Nothing happens. No content is added to the editor.

https://user-images.githubusercontent.com/58658048/110751542-47dd3b00-8244-11eb-9a9a-df995724f5b9.mp4

### Notes:
- DnD to Safari works from Firefox, other Safari window, or TextEdit
- my Safari version: 14.02
- my Word version: 16.44
- my OS: Big Sur 11.1

2021-03-11 13:51 UTC, oleq commented
## Steps to reproduce

1.  Visit [http://fake.ckeditor.com:8125/ckeditor5-clipboard/tests/manual/dragdrop.html.](http://fake.ckeditor.com:8125/ckeditor5-clipboard/tests/manual/dragdrop.html.)
2.  Drag a character card into the code block

## Expected

(most likely) nothing happens because cards cannot exist as code block content

## Actual

An error is thrown

```
utils.js:99 Uncaught TypeError: Cannot read property 'match' of undefined
    at getLeadingWhiteSpaces (utils.js:99)
    at getLastOutdentableSequenceRange (outdentcodeblockcommand.js:137)
    at outdentcodeblockcommand.js:108
    at Array.some (<anonymous>)
    at OutdentCodeBlockCommand._checkEnabled (outdentcodeblockcommand.js:107)
    at OutdentCodeBlockCommand.refresh (outdentcodeblockcommand.js:41)
    at Document.<anonymous> (command.js:111)
    at Document.fire (emittermixin.js:194)
    at Document._handleChangeBlock (document.js:309)
    at Model._runPendingChanges (model.js:833)
```

2021-03-11 13:54 UTC, oleq commented
The http://fake.ckeditor.com:8125/ckeditor5-clipboard/tests/manual/dropping.html manual test no longer makes sense (or at least its description starting with "There's no real drag&drop support yet.").

2021-03-11 14:02 UTC, oleq requested changes
The feature is excellent. 

I left some comments, also:

* The http://fake.ckeditor.com:8125/ckeditor5-clipboard/tests/manual/dropping.html manual test no longer makes sense (or at least its description starting with "There's no real drag&drop support yet.").

2021-03-11 14:04 UTC, niegowski commented on packages/ckeditor5-clipboard/src/clipboardpipeline.js
> + * It also handles the `cut` and `copy` events to fill the native clipboard with serialized editor's data.
hmm why it's outdated?

2021-03-11 14:17 UTC, oleq commented
The [http://fake.ckeditor.com:8125/ckeditor5-clipboard/tests/manual/dropping.html](http://fake.ckeditor.com:8125/ckeditor5-clipboard/tests/manual/dropping.html) manual test also stops/preventDefaults the drop event which makes the drop marker remain after the drop

![](https://user-images.githubusercontent.com/1099479/110800850-ebe2d880-827c-11eb-8c59-3b9e9e507074.gif)

2021-03-11 14:20 UTC, oleq commented
I'd also make the triangle on top of the marker flatter:

## Current

![](https://user-images.githubusercontent.com/1099479/110801133-319fa100-827d-11eb-98bb-2275ac3b6679.gif)

## Proposed

Using `border-width: 8px 6px 0 6px;`

![](https://user-images.githubusercontent.com/1099479/110801146-3401fb00-827d-11eb-83c6-c5db0632b348.gif)

WDYT @niegowski?

2021-03-11 14:57 UTC, niegowski commented
@ckeditor/qa-team could you please extract found issues (those that are still valid) to separate issues?

2021-03-11 15:37 UTC, merged