Docs: migration to 25 guide.
ckeditor/ckeditor5 pull request #9164
Opened 2021-03-04 13:53 UTC by godai78

Adding the Migration to v25.0.0 guide to the docs.

Closes: cksource/collaboration-features#3877

Necessary follow-up - link the guide in the CF changelog here: https://github.com/cksource/collaboration-features/blob/master/CHANGELOG.md#changes-in-the-annotations-api

2021-03-04 18:04 UTC, godai78 commented
@ckeditor/qa-team - guys, the same story, same error. Have a look at that, please?

2021-03-12 12:31 UTC, godai78 commented
CI'd properly, looks like good to go.

2021-03-23 15:03 UTC, AnnaTomanek requested changes

2021-03-23 15:03 UTC, AnnaTomanek commented on docs/builds/guides/migration/migration-to-25.0.0.md
> +* [`type`](https://ckeditor.com/docs/ckeditor5/latest/api/module_comments_annotations_annotation-Annotation.html#member-type) - The type of the annotation.
```suggestion
* [`type`](https://ckeditor.com/docs/ckeditor5/latest/api/module_comments_annotations_annotation-Annotation.html#member-type) &ndash; The type of the annotation.
```

2021-03-23 15:03 UTC, AnnaTomanek commented on docs/builds/guides/migration/migration-to-25.0.0.md
> +* [`isActive`](https://ckeditor.com/docs/ckeditor5/latest/api/module_comments_annotations_annotation-Annotation.html#member-isActive) - A property that determines if the annotation view and annotatio
```suggestion
* [`isActive`](https://ckeditor.com/docs/ckeditor5/latest/api/module_comments_annotations_annotation-Annotation.html#member-isActive) &ndash; A property that determines if the annotation view and annotation inner views are active or not. It should be changed by the annotation UI when it changes the active annotation.
```

2021-03-23 15:03 UTC, AnnaTomanek commented on docs/builds/guides/migration/migration-to-25.0.0.md
> +The [`Sidebar`](https://ckeditor.com/docs/ckeditor5/latest/api/module_comments_annotations_sidebar-Sidebar.html) class stopped operating on the global collection of annotations. From now on, the Anno
```suggestion
The [`Sidebar`](https://ckeditor.com/docs/ckeditor5/latest/api/module_comments_annotations_sidebar-Sidebar.html) class stopped operating on the global collection of annotations. From now on, the annotation UI that is responsible for displaying the sidebar should provide the sidebar with its collection of annotations and inform about possible actions with the new [`rearrange()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_comments_annotations_sidebar-Sidebar.html#function-rearrange) and [`refresh()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_comments_annotations_sidebar-Sidebar.html#function-refresh) methods.
```

2021-03-23 15:03 UTC, AnnaTomanek commented on docs/builds/guides/migration/migration-to-25.0.0.md
> +		// The code responsible for setting an active and non-active annotation based on the annotation focus changes.
```suggestion
		// The code responsible for setting an active and non-active annotation
		// based on the annotation focus changes.
```

2021-03-23 15:03 UTC, AnnaTomanek commented on docs/builds/guides/migration/migration-to-25.0.0.md
> +		// // If the plugin was initialized as an editor plugin, the integration should look like the following:
```suggestion
		// If the plugin was initialized as an editor plugin, the integration
		// should look like the following:
```

2021-03-23 15:03 UTC, AnnaTomanek commented on docs/builds/guides/migration/migration-to-26.0.0.md
>  category: builds-migration
```suggestion
category: builds-migration
menu-title: Migration to v26.0.0
```

2021-03-24 07:40 UTC, AnnaTomanek approved these changes

2021-03-24 07:40 UTC, merged