Add postfixer.
ckeditor/ckeditor5 pull request #9209
Opened 2021-03-11 08:23 UTC by maxbarnas

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Type: Message. Closes #000.

---

### Additional information

_For example – encountered issues, assumptions you had to make, other affected tickets, etc._

2021-03-30 18:10 UTC, niegowski requested changes

2021-03-30 20:23 UTC, maxbarnas commented on tests/manual/all-features.js
> -			CodeBlock, TodoList, ListStyle, TableProperties, TableCellProperties,
Also, the import is leftover from some manual tests. It's added properly in the next PR for Toolbar: https://github.com/ckeditor/ckeditor5/pull/9263/files#diff-f6c2d5e6eb1d6d18bc35b3d402a62943d48cb3ec0d38b533ae6824857c35ff48

2021-03-30 20:24 UTC, maxbarnas commented on tests/manual/all-features.js
> -			CodeBlock, TodoList, ListStyle, TableProperties, TableCellProperties,
And index.js is updated in the doc PR. What a mess 😂

2021-03-31 07:00 UTC, maxbarnas commented on packages/ckeditor5-table/src/commands/mergecellcommand.js
> +	if ( ( direction == 'down' && rowIndex === tableUtils.getRows( table ) - 1 ) || ( direction == 'up' && rowIndex === 0 ) ) {
Done.

2021-03-31 07:39 UTC, maxbarnas commented on packages/ckeditor5-table/src/commands/removerowcommand.js
> +			const cellToFocus = getCellToFocus( table, removedRowIndexes.first, columnIndexToFocus, tableUtils.getRows( table ) );
Done.

2021-03-31 08:46 UTC, maxbarnas commented on packages/ckeditor5-table/src/tablekeyboard.js
> +				if ( currentRowIndex === tableUtils.getRows( table ) - 1 ) {
Done.

2021-03-31 08:51 UTC, maxbarnas commented on packages/ckeditor5-table/src/tableutils.js
> +			.reduce( ( rowCount, child ) => child.is( 'element', 'tableRow' ) ? rowCount + 1 : rowCount, 0 );
Done.

2021-03-31 09:04 UTC, maxbarnas commented on packages/ckeditor5-table/src/tablewalker.js
> +		if ( !row || this._isOverEndRow() ) {
That change is actually the same as the code on `master` right now. I added tests for the block below though.

2021-03-31 12:28 UTC, maxbarnas commented on packages/ckeditor5-table/src/converters/table-layout-post-fixer.js
> +	const childrenLengths = getChildrenLengths( table );
Done.

2021-04-21 15:13 UTC, niegowski requested changes

2021-04-21 15:13 UTC, niegowski commented on packages/ckeditor5-table/tests/tableutils.js
> +			tableUtils.splitCellVertically( root.getNodeByPath( [ 0, 1, 0 ] ), 3 );
This should be checked for validity before calling this method.

2021-04-21 15:13 UTC, niegowski commented on packages/ckeditor5-table/tests/tableutils.js
> +			tableUtils.splitCellHorizontally( root.getNodeByPath( [ 0, 1, 0 ] ), 3 );
This should be checked for validity before calling this method.

2021-04-21 15:13 UTC, niegowski commented on packages/ckeditor5-table/tests/tableutils.js
> +		it( 'should return proper number of columns for a table with a non-row element', () => {
```suggestion
		it( 'should return proper number of rows for a table with a non-row element', () => {
```

2021-04-21 15:13 UTC, niegowski commented on packages/ckeditor5-table/src/tableutils.js
> +		const last = Math.min( first + rowsToRemove - 1, rowCount - 1 );
We should throw an error in case of invalid options.

2021-04-21 15:13 UTC, niegowski commented on packages/ckeditor5-table/tests/tableutils.js
> +				tableUtils.removeRows( root.getChild( 0 ), { at: 1, rows: 2 } );
This should throw.

2021-04-21 15:13 UTC, niegowski commented on packages/ckeditor5-table/tests/tableutils.js
> +				tableUtils.removeColumns( root.getChild( 0 ), { at: 1 } );
Maybe `at: 0` would make more sense?

2021-04-21 16:25 UTC, niegowski commented on packages/ckeditor5-table/src/tableutils.js
> +		}
This seems not to be needed.

2021-04-22 11:26 UTC, niegowski commented on packages/ckeditor5-table/tests/tableutils.js
> +					'tableutils-removerows-row-index-out-of-range'
The test description is invalid - it should throw for an out-of-range options.

2021-04-22 11:27 UTC, niegowski requested changes
As commented.

2021-04-22 11:37 UTC, niegowski approved these changes

2021-04-22 11:38 UTC, merged