Do not insert inline images inside code blocks
ckeditor/ckeditor5 pull request #9594
Opened 2021-04-29 12:21 UTC by pomek

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Fix (code-block): The code block feature will not allow for inserting inline images as its content. Closes #9567.

2021-04-29 15:01 UTC, oleq requested changes

2021-04-29 15:58 UTC, pomek commented on packages/ckeditor5-code-block/src/codeblockediting.js
> +				if ( context.endsWith( 'codeBlock' ) && childDefinition.name == 'imageInline' ) {
Yeah, I wasn't sure about it, but I couldn't figure out another use case. I'll improve it.

2021-04-29 16:13 UTC, pomek commented on packages/ckeditor5-code-block/src/codeblockediting.js
> +				if ( context.endsWith( 'codeBlock' ) && childDefinition.name == 'imageInline' ) {
@oleq, fixed.

2021-04-29 16:14 UTC, pomek commented on packages/ckeditor5-code-block/src/codeblockcommand.js
> +			// The `codeBlock` should contain only $text nodes as its children. See #9567.
```suggestion
			// The `codeBlock` element should contain only $text nodes as its children. See #9567.
```

2021-05-01 08:16 UTC, niegowski requested changes

2021-05-01 08:16 UTC, niegowski commented on packages/ckeditor5-code-block/src/codeblockcommand.js
> +				.forEach( writer.remove.bind( writer ) );
This is removing also the soft breaks: 

![](https://user-images.githubusercontent.com/1232187/116775776-12dfae80-aa65-11eb-96fb-3e9e529b1ec8.gif)

We should use schema to check for allowed children:

```suggestion
			// The `codeBlock` element should contain only $text nodes as its children. See #9567.
			Array.from( block.getChildren() )
				.filter( child => !schema.checkChild( block, child ) )
				.forEach( child => writer.remove( child ) );
```

![2021-05-01 10 09 13](https://user-images.githubusercontent.com/1232187/116775823-74a01880-aa65-11eb-9e25-99c68164873a.gif)

2021-05-04 12:25 UTC, niegowski approved these changes

2021-05-04 12:26 UTC, merged