Added option to remember the language when creating a new code block.
ckeditor/ckeditor5 pull request #9840
Opened 2021-06-09 10:35 UTC by przemyslaw-zan

### Suggested merge commit message ([convention](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/git-commit-message-convention.html))

Feature: Added option to remember the language when creating a new code block. Closes #8722.

---

### Additional information

The option is off by default.

2021-06-09 10:43 UTC, przemyslaw-zan commented
A few tests are missing. I’ll add them, and once it is done, I’ll let you know.

2021-06-10 12:14 UTC, pomek requested changes
As mentioned.

2021-06-10 12:14 UTC, pomek commented on packages/ckeditor5-code-block/src/codeblockcommand.js
> +	 * @param {String|null} [options.language] Language picked from dropdown.
```suggestion
	 * @param {String} [options.language] The code block language.
```

1. When setting `options.language` to `null`, the command will use the default language. So it does not have to be specified. So, for example, `{String}` will be enough.
	* `[` and `]` marks the argument as optional, so if an integrator does not specify the value, the command will still work.
1. The language option does not have to come from the dropdown. The integrator can just execute the command directly: `editor.execute( 'codeBlock', { language: 'php' } )`. 
    * We do not have to focus on where the value comes from but what it does.

2021-06-10 12:14 UTC, pomek commented on packages/ckeditor5-code-block/src/codeblockcommand.js
> +	 * @param {Boolean} [options.usePreviousLanguageChoice=true] Defines whether or not button will create code block with the same
```suggestion
	 * @param {Boolean} [options.usePreviousLanguageChoice] If set on `true` and the `options.language` is not specified, the command will apply the previous language (if the command was already executed) when inserting the `codeBlock` element.
```

1. `options.usePreviousLanguageChoice` is marked as optional (`[]`). If not specified, it's a false value (`undefined`).
1. The command itself does not know about the UI, so it does not know what the "button" is.

2021-06-10 12:14 UTC, pomek commented on packages/ckeditor5-code-block/src/codeblockcommand.js
> +	}
```suggestion
	if ( options.language ) {
		return options.language;
	}

	if ( options.usePreviousLanguageChoice && lastLanguage ) {
		return lastLanguage;
	}
```

I'd swap the order of these conditions. If the `options.language` is specified, it should be used. Please, do not update the function docs.

2021-06-10 12:14 UTC, pomek commented on packages/ckeditor5-code-block/src/codeblockcommand.js
> +	}
One more thing, make sure that the change is covered by a test (in the `CodeBlockCommand` file).

2021-06-10 12:14 UTC, pomek commented on packages/ckeditor5-code-block/tests/codeblockcommand.js
> +		} );
We need one more test that will cover a change described in the `getLanguage()` function.

```js
# Mock the "last language"
command._lastLanguage = 'css';

# Then execute the command, but with the specified language:
command.execute( { language: 'php', usePreviousLanguageChoice: true } );

# Expecting that the codeBlock will use `php` as the language.
```

I agree these options are mutually exclusive, but we can handle it and use the provided language.

2021-06-11 07:25 UTC, pomek commented on packages/ckeditor5-code-block/src/codeblockcommand.js
> +	 * language as the previous code block.
```suggestion
```

2021-06-11 07:26 UTC, pomek approved these changes
LGTM.

2021-06-11 07:26 UTC, merged